// ─── HelpEntry ──────────────────────────────────────────────────────────────

export interface HelpEntry {
  title: string;
  whatItChanges: string;
  higherValue: string;
  lowerValue: string;
  tradeoff: string;
  bandwidth: "increase" | "decrease" | "none" | "variable";
  sharpness: "increase" | "decrease" | "none";
  motion: "increase" | "decrease" | "none";
  cpu: "increase" | "decrease" | "none";
  latency: "increase" | "decrease" | "none";
  compatibility: "increase" | "decrease" | "none";
  perViewer: boolean;
  hostWide: boolean;
  liveSafe: boolean;
  restartRequired: boolean;
}

// ─── Help Entries ───────────────────────────────────────────────────────────

export const HELP_ENTRIES: Record<string, HelpEntry> = {
  // ── Video ───────────────────────────────────────────────────────────────────

  videoBitrateKbps: {
    title: "Video Bitrate",
    whatItChanges: "The number of kilobits per second allocated to the video stream. Higher values produce clearer picture but use more network bandwidth.",
    higherValue: "Sharper image, fewer compression artifacts, better for high-motion content",
    lowerValue: "Lower network usage, smoother playback on slow connections, but more visible compression artifacts",
    tradeoff: "Bandwidth vs. quality — more bitrate looks better but consumes more network capacity",
    bandwidth: "increase",
    sharpness: "increase",
    motion: "increase",
    cpu: "none",
    latency: "none",
    compatibility: "none",
    perViewer: true,
    hostWide: true,
    liveSafe: true,
    restartRequired: false,
  },

  sendWidth: {
    title: "Send Width",
    whatItChanges: "The horizontal resolution (in pixels) of the video stream sent to viewers. Controls how wide the output picture is.",
    higherValue: "Wider, more detailed picture, better for wide-screen content and fine text",
    lowerValue: "Narrower picture, less detail but lower bandwidth and CPU usage",
    tradeoff: "Resolution vs. bandwidth/CPU — wider is sharper but more expensive",
    bandwidth: "increase",
    sharpness: "increase",
    motion: "none",
    cpu: "increase",
    latency: "none",
    compatibility: "none",
    perViewer: false,
    hostWide: true,
    liveSafe: true,
    restartRequired: true,
  },

  sendHeight: {
    title: "Send Height",
    whatItChanges: "The vertical resolution (in pixels) of the video stream sent to viewers. Controls how tall the output picture is.",
    higherValue: "Taller, more detailed picture, better for reading documents with vertical content",
    lowerValue: "Shorter picture, less detail but lower bandwidth and CPU usage",
    tradeoff: "Resolution vs. bandwidth/CPU — taller is sharper but more expensive",
    bandwidth: "increase",
    sharpness: "increase",
    motion: "none",
    cpu: "increase",
    latency: "none",
    compatibility: "none",
    perViewer: false,
    hostWide: true,
    liveSafe: true,
    restartRequired: true,
  },

  sendFps: {
    title: "Send Framerate",
    whatItChanges: "The number of frames per second (fps) transmitted to viewers. Controls how smooth motion appears.",
    higherValue: "Smoother motion, better for video, animations, and scrolling",
    lowerValue: "Lower bandwidth and CPU usage, adequate for static content like documents",
    tradeoff: "Motion smoothness vs. bandwidth/CPU — higher fps is smoother but more expensive",
    bandwidth: "increase",
    sharpness: "none",
    motion: "increase",
    cpu: "increase",
    latency: "none",
    compatibility: "none",
    perViewer: true,
    hostWide: true,
    liveSafe: true,
    restartRequired: false,
  },

  captureWidth: {
    title: "Capture Width",
    whatItChanges: "The horizontal resolution (in pixels) at which the source is captured before encoding. Affects the raw capture quality.",
    higherValue: "More source detail preserved, better for zooming and fine text",
    lowerValue: "Lower capture overhead, less memory usage",
    tradeoff: "Capture quality vs. memory/performance — higher is better but more resource-intensive",
    bandwidth: "increase",
    sharpness: "increase",
    motion: "none",
    cpu: "increase",
    latency: "increase",
    compatibility: "none",
    perViewer: false,
    hostWide: true,
    liveSafe: false,
    restartRequired: true,
  },

  captureHeight: {
    title: "Capture Height",
    whatItChanges: "The vertical resolution (in pixels) at which the source is captured before encoding. Affects the raw capture quality.",
    higherValue: "More source detail preserved, better for vertical content",
    lowerValue: "Lower capture overhead, less memory usage",
    tradeoff: "Capture quality vs. memory/performance — higher is better but more resource-intensive",
    bandwidth: "increase",
    sharpness: "increase",
    motion: "none",
    cpu: "increase",
    latency: "increase",
    compatibility: "none",
    perViewer: false,
    hostWide: true,
    liveSafe: false,
    restartRequired: true,
  },

  captureFps: {
    title: "Capture Framerate",
    whatItChanges: "The framerate at which the source is captured. Determines the maximum possible output framerate.",
    higherValue: "Smoother source capture, better for video and fast motion",
    lowerValue: "Lower CPU usage, adequate for static content",
    tradeoff: "Capture smoothness vs. CPU — higher fps captures more detail but uses more CPU",
    bandwidth: "increase",
    sharpness: "none",
    motion: "increase",
    cpu: "increase",
    latency: "increase",
    compatibility: "none",
    perViewer: false,
    hostWide: true,
    liveSafe: false,
    restartRequired: true,
  },

  codec: {
    title: "Video Codec",
    whatItChanges: "The compression algorithm used to encode the video stream. Different codecs offer different quality/speed/ compatibility tradeoffs.",
    higherValue: "VP9/AV1 give better quality at same bitrate but require more CPU; AV1 has limited hardware support",
    lowerValue: "H264/VP8 are more widely compatible and faster to encode but need higher bitrate for same quality",
    tradeoff: "Efficiency vs. compatibility — modern codecs save bandwidth but may not play everywhere",
    bandwidth: "variable",
    sharpness: "increase",
    motion: "none",
    cpu: "increase",
    latency: "increase",
    compatibility: "decrease",
    perViewer: false,
    hostWide: true,
    liveSafe: false,
    restartRequired: true,
  },

  contentHint: {
    title: "Content Hint",
    whatItChanges: "Tells the encoder what kind of content is being streamed so it can optimize compression strategy.",
    higherValue: "MOTION — optimizes for smooth video playback, best for moving content",
    lowerValue: "TEXT — optimizes for sharp text and fine details, best for documents and code",
    tradeoff: "Motion vs. detail — encoders tune differently for text vs. video content",
    bandwidth: "variable",
    sharpness: "variable",
    motion: "variable",
    cpu: "none",
    latency: "none",
    compatibility: "none",
    perViewer: false,
    hostWide: true,
    liveSafe: true,
    restartRequired: false,
  },

  degradationPreference: {
    title: "Degradation Preference",
    whatItChanges: "Controls how the encoder responds when bandwidth is limited — whether to drop resolution or framerate first.",
    higherValue: "MAINTAIN-RESOLUTION — keeps picture sharp but may lower framerate during congestion",
    lowerValue: "MAINTAIN-FRAMERATE — keeps motion smooth but may lower resolution during congestion",
    tradeoff: "Resolution vs. framerate under duress — choose what matters more for your content",
    bandwidth: "none",
    sharpness: "variable",
    motion: "variable",
    cpu: "none",
    latency: "none",
    compatibility: "none",
    perViewer: true,
    hostWide: true,
    liveSafe: true,
    restartRequired: false,
  },

  scalabilityMode: {
    title: "Scalability Mode",
    whatItChanges: "Enables SVC (Scalable Video Coding) temporal/spatial layers, allowing the stream to adapt to different viewer capabilities.",
    higherValue: "L3T3 — three temporal and three spatial layers, maximum adaptability but higher overhead",
    lowerValue: "Disabled (null) — no SVC layers, simpler encoding but no adaptation within the stream",
    tradeoff: "Adaptability vs. overhead — SVC layers allow per-viewer quality but increase encoder complexity",
    bandwidth: "increase",
    sharpness: "none",
    motion: "increase",
    cpu: "increase",
    latency: "none",
    compatibility: "decrease",
    perViewer: true,
    hostWide: true,
    liveSafe: false,
    restartRequired: true,
  },

  h264Profile: {
    title: "H264 Profile",
    whatItChanges: "Which subset of H264 features the encoder uses. Higher profiles enable better compression but may not be supported on older devices.",
    higherValue: "HIGH — best compression efficiency, requires newer hardware decoders",
    lowerValue: "BASELINE — maximum compatibility with older devices, lower compression efficiency",
    tradeoff: "Compatibility vs. efficiency — higher profiles save bandwidth but may not play everywhere",
    bandwidth: "decrease",
    sharpness: "none",
    motion: "none",
    cpu: "none",
    latency: "none",
    compatibility: "decrease",
    perViewer: false,
    hostWide: true,
    liveSafe: false,
    restartRequired: true,
  },

  // ── Audio ───────────────────────────────────────────────────────────────────

  audioBitrateKbps: {
    title: "Audio Bitrate",
    whatItChanges: "The number of kilobits per second allocated to the audio stream. Higher values produce clearer audio.",
    higherValue: "Better audio clarity, especially for music and complex soundscapes",
    lowerValue: "Lower network usage, adequate for speech but may have audible artifacts for music",
    tradeoff: "Audio quality vs. bandwidth — higher bitrate sounds better but uses more bandwidth",
    bandwidth: "increase",
    sharpness: "none",
    motion: "none",
    cpu: "none",
    latency: "none",
    compatibility: "none",
    perViewer: false,
    hostWide: true,
    liveSafe: true,
    restartRequired: false,
  },

  audioDtx: {
    title: "DTX (Discontinuous Transmission)",
    whatItChanges: "Controls whether audio packets are suppressed during silence periods to save bandwidth.",
    higherValue: "Enabled — stops sending packets during silence, saving significant bandwidth",
    lowerValue: "Disabled — continuously sends audio packets even during silence, uses more bandwidth",
    tradeoff: "Bandwidth savings vs. possible audio cut-off — DTX saves bandwidth but may clip very quiet sounds",
    bandwidth: "decrease",
    sharpness: "none",
    motion: "none",
    cpu: "none",
    latency: "none",
    compatibility: "none",
    perViewer: false,
    hostWide: true,
    liveSafe: true,
    restartRequired: false,
  },

  audioFec: {
    title: "FEC (Forward Error Correction)",
    whatItChanges: "Adds redundant audio data to the stream so lost packets can be recovered without retransmission.",
    higherValue: "Enabled — better audio reliability on lossy networks, but increases bandwidth usage",
    lowerValue: "Disabled — no redundancy overhead, but audio may glitch on packet loss",
    tradeoff: "Reliability vs. bandwidth — FEC protects against packet loss at the cost of extra data",
    bandwidth: "increase",
    sharpness: "none",
    motion: "none",
    cpu: "none",
    latency: "decrease",
    compatibility: "none",
    perViewer: false,
    hostWide: true,
    liveSafe: true,
    restartRequired: false,
  },

  audioChannels: {
    title: "Audio Channels",
    whatItChanges: "Whether audio is captured in mono or stereo. Stereo provides spatial audio but uses more bandwidth.",
    higherValue: "STEREO — two-channel audio with spatial separation, better for music and immersive experiences",
    lowerValue: "MONO — single-channel audio, uses half the bandwidth, adequate for speech",
    tradeoff: "Spatial audio vs. bandwidth — stereo sounds fuller but uses more data",
    bandwidth: "increase",
    sharpness: "none",
    motion: "none",
    cpu: "none",
    latency: "none",
    compatibility: "none",
    perViewer: false,
    hostWide: true,
    liveSafe: true,
    restartRequired: false,
  },

  audioBitrateMode: {
    title: "Audio Bitrate Mode",
    whatItChanges: "Whether the audio encoder uses a constant or variable bitrate.",
    higherValue: "CBR (Constant Bitrate) — predictable bandwidth usage, may waste bits on simple audio",
    lowerValue: "VBR (Variable Bitrate) — more efficient, uses fewer bits for simple audio, more for complex audio",
    tradeoff: "Consistency vs. efficiency — CBR is predictable, VBR is more efficient",
    bandwidth: "variable",
    sharpness: "none",
    motion: "none",
    cpu: "none",
    latency: "none",
    compatibility: "none",
    perViewer: false,
    hostWide: true,
    liveSafe: true,
    restartRequired: false,
  },

  audioPacketDurationMs: {
    title: "Audio Packet Duration",
    whatItChanges: "The duration of audio in each packet. Shorter durations reduce latency but increase overhead.",
    higherValue: "60ms — lower overhead and bandwidth, but adds more latency",
    lowerValue: "10ms — lower latency, better for real-time interaction, but more packet overhead",
    tradeoff: "Latency vs. overhead — shorter packets reduce delay at the cost of more headers",
    bandwidth: "decrease",
    sharpness: "none",
    motion: "none",
    cpu: "none",
    latency: "increase",
    compatibility: "none",
    perViewer: false,
    hostWide: true,
    liveSafe: true,
    restartRequired: false,
  },

  audioRedundantAudio: {
    title: "Redundant Audio",
    whatItChanges: "Sends duplicate audio data for the most recent packets, enabling recovery from packet loss without retransmission.",
    higherValue: "Enabled — better loss recovery but increases bandwidth usage significantly",
    lowerValue: "Disabled — no redundancy, but audio may drop out during packet loss",
    tradeoff: "Reliability vs. bandwidth — redundancy helps recover from loss but nearly doubles audio bandwidth",
    bandwidth: "increase",
    sharpness: "none",
    motion: "none",
    cpu: "none",
    latency: "none",
    compatibility: "none",
    perViewer: false,
    hostWide: true,
    liveSafe: true,
    restartRequired: false,
  },
};
