import type { GroupControlEnvelope } from "@screenlink/shared";
import type { Phase3Runtime } from "./phase3-runtime.js";

/**
 * Binding token created by the host for a viewer's stream.join.request.
 * The viewer must present this token via media.bind to be granted a peer connection.
 */
export interface BindingToken {
  token: string;
  groupId: string;
  logicalStreamId: string;
  mediaSessionId: string;
  viewerDeviceId: string;
  /**
   * Per-attempt session ID generated by the viewer for every Watch attempt.
   * Carried through the join → bind → leave flow so the host can
   * disambiguate attempts that share the same viewerDeviceId.
   */
  viewerSessionId: string;
  createdAt: number;
  expiresAt: number;
  consumed: boolean;
}

/**
 * Extended viewer mapping with complete binding context.
 * Stores enough information to support exact viewer operations:
 * sender quality apply, per-viewer stats, and deterministic cleanup.
 */
export interface ViewerMapping {
  viewerDeviceId: string;
  /**
   * Per-attempt session ID for this viewer. A new Watch attempt by the
   * same device gets a new ID; the host uses it to reject stale leave
   * messages that were sent by a prior attempt before the user re-joined.
   */
  viewerSessionId: string;
  mediaPeerUuid: string;
  groupId: string;
  logicalStreamId: string;
  mediaSessionId: string;
  /** The RTCPeerConnection for this viewer's media, used for sender access and stats */
  pc: RTCPeerConnection | null;
  /** The video RTCRtpSender for this viewer, used for quality application */
  videoSender: RTCRtpSender | null;
  /** The audio RTCRtpSender for this viewer, used for diagnostics and per-viewer audio control */
  audioSender: RTCRtpSender | null;
}

export interface ConsumeBindingInput {
  token: string;
  viewerDeviceId: string;
  /**
   * Per-attempt session ID. Must match the token's stored ID for the
   * binding to be accepted — prevents a delayed bind from a prior
   * attempt from being mis-applied to a newer session.
   */
  viewerSessionId: string;
  groupId: string;
  logicalStreamId: string;
  mediaSessionId: string;
  mediaPeerUuid: string;
}

/**
 * C5: ViewerMediaBinding (Stages 4–5)
 *
 * Manages one-time binding tokens that authorize a viewer to attach
 * to a specific media session. The host:
 * 1. Receives stream.join.request → generates token
 * 2. Viewer presents token via media.bind data channel message
 * 3. Host validates and marks consumed
 *
 * Stage 5 enhancements:
 * - consumeBinding(): full validation of token + viewer/group/logicalStream/mediaSession/peerConnection/senders
 * - Duplicate request idempotency via requestId tracking
 * - getAllViewers() for cleanup on stream stop
 * - Viewer disconnect preserves other viewers
 */
export class ViewerMediaBinding {
  private tokens = new Map<string, BindingToken>();
  /** viewerDeviceId → media peer mapping */
  private viewerMap = new Map<string, ViewerMapping>();
  /** Track processed requestIds for idempotency */
  private processedRequests = new Map<string, string>(); // requestEnvelopeId → token
  private cleanupTimer: ReturnType<typeof setInterval> | null = null;
  private destroyed = false;
  private readonly TOKEN_TTL_MS = 60_000; // 60 seconds
  private readonly CLEANUP_INTERVAL_MS = 30_000; // every 30s

  constructor(private runtime: Phase3Runtime) {
    this.startCleanup();
  }

  /**
   * Called by host when stream.join.request arrives via group control.
   * Validates the sender has a valid group with an active stream,
   * generates a one-time token, stores it, and sends a response back
   * to the requesting viewer via group control.
   *
   * Uses the real host device ID from the runtime (not hardcoded "local").
   * Stage 5: Duplicate requestId returns the same token (idempotent).
   *
   * Returns null if no active stream is found for the group (but sends
   * an explicit rejection so the viewer does not time out). Returns
   * null on other failures as well.
   */
  handleJoinRequest(envelope: GroupControlEnvelope): { mediaSessionId: string; token: string; viewerSessionId: string } | null {
    if (this.destroyed) return null;

    const groupId = envelope.groupId;
    const viewerDeviceId = envelope.senderDeviceId;
    const payload = envelope.payload as Record<string, unknown> | undefined;
    const logicalStreamId = payload?.logicalStreamId as string | undefined;
    const requestId = payload?.requestId as string | undefined;
    // Optional per-attempt session ID. If the viewer is on an older build
    // that doesn't generate one, we synthesize a stable identifier from
    // the envelope's messageId so the token still carries something the
    // host can use to reject stale leaves for THIS specific attempt.
    const viewerSessionId =
      (payload?.viewerSessionId as string | undefined) ??
      (envelope.messageId ?? `legacy-${viewerDeviceId ?? "unknown"}-${requestId ?? Date.now().toString()}`);

    if (!viewerDeviceId || !logicalStreamId) {
      // Send rejection for invalid request so the viewer doesn't time out
      this.sendJoinRejection(
        envelope,
        requestId,
        !viewerDeviceId ? "Invalid viewer identity" : "Missing stream identifier",
      );
      return null;
    }

    // Stage 5: Check for duplicate request (same envelope messageId)
    if (envelope.messageId && this.processedRequests.has(envelope.messageId)) {
      const existingToken = this.processedRequests.get(envelope.messageId)!;
      const bt = this.tokens.get(existingToken);
      if (bt && !bt.consumed) {
        return { mediaSessionId: bt.mediaSessionId, token: existingToken, viewerSessionId: bt.viewerSessionId };
      }
    }

    // Use the real host device ID from the runtime, not hardcoded "local"
    const hostDeviceId = this.runtime.deviceId ?? "local";

    // Verify this group has an active stream matching the request
    const registry = this.runtime.getActiveStreamRegistry();
    const stream = registry.getStream({
      groupId,
      hostDeviceId,
      logicalStreamId,
    });
    if (!stream) {
      // Send explicit rejection instead of forcing a timeout
      this.sendJoinRejection(
        envelope,
        requestId,
        "There is no active share for this stream",
      );
      return null;
    }

    // Generate 32 random bytes → Base64URL token
    const rawBytes = new Uint8Array(32);
    crypto.getRandomValues(rawBytes);
    const token = this.base64URLEncode(rawBytes);

    const now = Date.now();
    const bindingToken: BindingToken = {
      token,
      groupId,
      logicalStreamId,
      mediaSessionId: stream.mediaSessionId,
      viewerDeviceId,
      viewerSessionId,
      createdAt: now,
      expiresAt: now + this.TOKEN_TTL_MS,
      consumed: false,
    };

    this.tokens.set(token, bindingToken);

    // Track for idempotency
    if (envelope.messageId) {
      this.processedRequests.set(envelope.messageId, token);
    }

    // Send join response back to the requesting viewer
    this.sendJoinResponse(envelope, token, stream.mediaSessionId, requestId, viewerSessionId).catch(() => {});

    return {
      mediaSessionId: stream.mediaSessionId,
      token,
      viewerSessionId,
    };
  }

  /**
   * Send a stream.join.response with accepted=false and a user-facing reason.
   * Prevents the viewer from timing out when the host cannot satisfy the request
   * (e.g. no active stream, invalid parameters).
   */
  private async sendJoinRejection(
    requestEnvelope: GroupControlEnvelope,
    requestId: string | undefined,
    reason: string,
  ): Promise<void> {
    const conn = this.runtime.getConnectionManager().getConnection(requestEnvelope.groupId);
    if (!conn) return;
    const peerUuid = conn.peerForDevice(requestEnvelope.senderDeviceId);
    if (!peerUuid) return;

    const payload = requestEnvelope.payload as Record<string, unknown> | undefined;
    const viewerSessionId = payload?.viewerSessionId as string | undefined;

    try {
      await conn.sendToPeer(peerUuid, {
        type: "stream.join.response",
        logicalStreamId: (payload?.logicalStreamId as string) ?? "",
        accepted: false,
        viewerDeviceId: requestEnvelope.senderDeviceId,
        reason,
        requestId: requestId ?? "",
        ...(viewerSessionId ? { viewerSessionId } : {}),
      });
    } catch {
      // Best-effort rejection — if the connection is gone the viewer will time out
    }
  }

  /**
   * Send a stream.join.response back to the requesting viewer via group control.
   * Includes VDO media credentials (streamId, password, bindingToken) so the
   * viewer can connect directly via ViewerClient without local host config.
   */
  private async sendJoinResponse(
    requestEnvelope: GroupControlEnvelope,
    token: string,
    mediaSessionId: string,
    requestId?: string,
    viewerSessionId?: string,
  ): Promise<void> {
    const conn = this.runtime.getConnectionManager().getConnection(requestEnvelope.groupId);
    if (!conn) return;
    const peerUuid = conn.peerForDevice(requestEnvelope.senderDeviceId);
    if (!peerUuid) return;

    // Get VDO credentials from the StreamSessionManager so the viewer can
    // connect directly via ViewerClient with the real streamId & password.
    const ssm = this.runtime.getStreamSessionManager();
    const vdoConfig = ssm.getCurrentVdoConfig();

    await conn.sendToPeer(peerUuid, {
      type: "stream.join.response",
      logicalStreamId: requestEnvelope.payload?.logicalStreamId as string,
      accepted: true,
      viewerDeviceId: requestEnvelope.senderDeviceId,
      mediaSessionId,
      mediaJoinMetadata: token,
      streamId: vdoConfig?.streamId,
      password: vdoConfig?.password,
      bindingToken: token,
      requestId: requestId ?? "",
      ...(viewerSessionId ? { viewerSessionId } : {}),
    });
  }

  /**
   * Called by host when media.bind arrives via the VDO data channel.
   * Uses the real media peer UUID from the VDO SDK callback.
   *
   * Delegates to consumeBinding() with the token's stored context
   * for consistent validation across both bind paths.
   */
  async handleMediaBind(peerUuid: string, token: string, viewerSessionId?: string): Promise<boolean> {
    if (this.destroyed) return false;

    const bindingToken = this.tokens.get(token);
    if (!bindingToken) return false;
    if (bindingToken.consumed) return false;
    if (Date.now() > bindingToken.expiresAt) {
      this.tokens.delete(token);
      return false;
    }

    // Use the full consumeBinding path for consistent validation
    return this.consumeBinding({
      token,
      viewerDeviceId: bindingToken.viewerDeviceId,
      viewerSessionId: viewerSessionId ?? bindingToken.viewerSessionId,
      groupId: bindingToken.groupId,
      logicalStreamId: bindingToken.logicalStreamId,
      mediaSessionId: bindingToken.mediaSessionId,
      mediaPeerUuid: peerUuid,
    });
  }

  /**
   * Stage 5: Full binding consumption with validation.
   *
   * Validates that:
   * - The token exists and is not consumed
   * - The viewerDeviceId matches
   * - The viewerSessionId matches (when supplied)
   * - The groupId matches
   * - The logicalStreamId matches
   * - The mediaSessionId matches
   *
   * On success, deletes the token and stores the viewer mapping.
   * Returns true if the binding was consumed successfully.
   */
  async consumeBinding(input: ConsumeBindingInput): Promise<boolean> {
    if (this.destroyed) return false;

    const bindingToken = this.tokens.get(input.token);
    if (!bindingToken) return false;
    if (bindingToken.consumed) return false;
    if (Date.now() > bindingToken.expiresAt) {
      this.tokens.delete(input.token);
      return false;
    }

    // Validate viewerDeviceId
    if (bindingToken.viewerDeviceId !== input.viewerDeviceId) return false;

    // Validate viewerSessionId when both sides have one. If the bind
    // payload omits a session ID but the token has one, we treat that
    // as a mismatch — the viewer's own join request generated the token
    // with a session ID, so any subsequent bind must carry the same one.
    if (input.viewerSessionId && bindingToken.viewerSessionId &&
        input.viewerSessionId !== bindingToken.viewerSessionId) {
      return false;
    }

    // Validate groupId
    if (bindingToken.groupId !== input.groupId) return false;

    // Validate logicalStreamId
    if (bindingToken.logicalStreamId !== input.logicalStreamId) return false;

    // Validate mediaSessionId
    if (bindingToken.mediaSessionId !== input.mediaSessionId) return false;

    // Mark consumed and delete token
    bindingToken.consumed = true;
    this.tokens.delete(input.token);

    // Try to resolve the RTCPeerConnection, video sender, and audio sender for this viewer
    let pc: RTCPeerConnection | null = null;
    let videoSender: RTCRtpSender | null = null;
    let audioSender: RTCRtpSender | null = null;
    try {
      const publisherManager = this.runtime.getStreamSessionManager().getPublisherManager();
      const hostPublisher = publisherManager?.getPublisher();
      if (hostPublisher) {
        const sdk = hostPublisher.getSDK();
        if (sdk && sdk.connections) {
          const group = sdk.connections.get(input.mediaPeerUuid);
          if (group) {
            pc = group.publisher?.pc ?? group.viewer?.pc ?? null;
            if (pc) {
              const senders = pc.getSenders();
              videoSender = senders.find(s => s.track?.kind === "video") ?? null;
              audioSender = senders.find(s => s.track?.kind === "audio") ?? null;
            }
          }
        }
      }
    } catch {
      // Sender/PC resolution is best-effort
    }

    // Store extended viewer mapping with peer connection and sender references.
    // The viewer's per-attempt session ID is stored alongside the device ID so
    // stale leave messages from a prior attempt can be ignored.
    this.viewerMap.set(input.viewerDeviceId, {
      viewerDeviceId: input.viewerDeviceId,
      viewerSessionId: input.viewerSessionId ?? bindingToken.viewerSessionId,
      mediaPeerUuid: input.mediaPeerUuid,
      groupId: input.groupId,
      logicalStreamId: input.logicalStreamId,
      mediaSessionId: input.mediaSessionId,
      pc,
      videoSender,
      audioSender,
    });

    // Start per-viewer stats polling when binding is established
    if (pc) {
      const statsService = this.runtime.getMediaStatsService();
      if (statsService) {
        statsService.startViewerPoller(
          input.groupId,
          input.logicalStreamId,
          input.viewerDeviceId,
          input.mediaPeerUuid,
          pc,
          () => {
            // Stats callback — no-op for now, stats flow through store in future
          },
        );
      }
    }

    return true;
  }

  /**
   * Get the media peer UUID for a viewer device ID.
   * Returns null if not found.
   */
  getViewerMediaPeer(viewerDeviceId: string): string | null {
    return this.viewerMap.get(viewerDeviceId)?.mediaPeerUuid ?? null;
  }

  /**
   * Remove a viewer from the binding map.
   *
   * Accepts an optional `viewerSessionId`. When provided, the mapping is
   * only removed if the stored session ID matches. This prevents a
   * delayed `stream.leave` from a prior Watch attempt from clobbering a
   * newer active mapping for the same device.
   *
   * Cleanup is restricted to ScreenLink-owned state (mapping entry,
   * per-viewer stats polling). The peer connection is owned by the
   * VDO.Ninja SDK and is closed by the SDK itself when the viewer
   * tears down; closing it here is unsafe because it can leave the
   * SDK's internal connection map in a broken state.
   */
  removeViewer(viewerDeviceId: string, viewerSessionId?: string): boolean {
    const mapping = this.viewerMap.get(viewerDeviceId);
    if (!mapping) return false;

    // Stale leave guard: if the caller provided a session ID and it
    // does not match the active mapping, ignore the message. A new
    // Watch attempt has the same viewerDeviceId but a different
    // session ID, and we must not remove the new mapping on behalf
    // of the old one.
    if (viewerSessionId && mapping.viewerSessionId &&
        viewerSessionId !== mapping.viewerSessionId) {
      console.warn(
        '[ViewerMediaBinding] ignoring stream.leave for stale viewerSessionId',
        {
          viewerDeviceId,
          incoming: viewerSessionId,
          active: mapping.viewerSessionId,
        },
      );
      return false;
    }

    // Note: we DO NOT call mapping.pc.close() here. The peer connection
    // belongs to the VDO.Ninja SDK; closing it directly leaves the SDK
    // in a broken state and is the root cause of repeated-rejoin
    // failures. The SDK closes the PC when the viewer disconnects or
    // when the publisher is torn down.

    // Stop per-viewer stats polling
    const statsService = this.runtime.getMediaStatsService();
    if (statsService) {
      statsService.disconnectViewer(
        mapping.groupId,
        mapping.logicalStreamId,
        viewerDeviceId,
        mapping.mediaPeerUuid,
      );
    }

    this.viewerMap.delete(viewerDeviceId);
    return true;
  }

  /**
   * Remove a viewer by media peer UUID. Used by the host's SDK
   * `peerDisconnected` handler so that an abrupt disconnect (where
   * no `stream.leave` ever arrives) still cleans up ScreenLink-owned
   * state. The PC close itself is left to the SDK.
   */
  removeViewerByPeerUuid(mediaPeerUuid: string): boolean {
    for (const [viewerDeviceId, mapping] of this.viewerMap) {
      if (mapping.mediaPeerUuid === mediaPeerUuid) {
        return this.removeViewer(viewerDeviceId, mapping.viewerSessionId);
      }
    }
    return false;
  }

  /**
   * Stage 5: Get all mapped viewers.
   * Used by StreamSessionManager.stopStream() to clean up on stream stop.
   */
  getAllViewers(): ViewerMapping[] {
    return Array.from(this.viewerMap.values());
  }

  /**
   * Get the video RTCRtpSender for a specific viewer.
   * Returns null if the viewer is not mapped or sender is unavailable.
   * Used by QualityCoordinator to apply per-viewer quality.
   */
  getViewerVideoSender(viewerDeviceId: string): RTCRtpSender | null {
    return this.viewerMap.get(viewerDeviceId)?.videoSender ?? null;
  }

  /**
   * Get the audio RTCRtpSender for a specific viewer.
   * Returns null if the viewer is not mapped or sender is unavailable.
   * Used for per-viewer audio diagnostics and control.
   */
  getViewerAudioSender(viewerDeviceId: string): RTCRtpSender | null {
    return this.viewerMap.get(viewerDeviceId)?.audioSender ?? null;
  }

  /**
   * Get the RTCPeerConnection for a specific viewer.
   * Returns null if the viewer is not mapped or PC is unavailable.
   * Used for per-viewer stats polling and diagnostics.
   */
  getViewerPeerConnection(viewerDeviceId: string): RTCPeerConnection | null {
    return this.viewerMap.get(viewerDeviceId)?.pc ?? null;
  }

  /**
   * Get full viewer mapping for a device ID.
   * Returns null if viewer is not mapped.
   */
  getViewerMapping(viewerDeviceId: string): ViewerMapping | null {
    return this.viewerMap.get(viewerDeviceId) ?? null;
  }

  /**
   * Get the binding token for diagnostics/debugging.
   */
  getBindingToken(token: string): BindingToken | undefined {
    return this.tokens.get(token);
  }

  /**
   * Destroy the binding manager. Terminates cleanup timer and clears all state.
   */
  destroy(): void {
    this.destroyed = true;
    this.tokens.clear();
    this.viewerMap.clear();
    this.processedRequests.clear();
    if (this.cleanupTimer) {
      clearInterval(this.cleanupTimer);
      this.cleanupTimer = null;
    }
  }

  // ── Private ──────────────────────────────────────────────────

  private startCleanup(): void {
    if (this.cleanupTimer) return;
    this.cleanupTimer = setInterval(() => {
      this.cleanupExpiredTokens();
    }, this.CLEANUP_INTERVAL_MS);
  }

  private cleanupExpiredTokens(): void {
    const now = Date.now();
    for (const [token, bt] of this.tokens) {
      if (now > bt.expiresAt) {
        this.tokens.delete(token);
      }
    }
    // Also clean up stale processed request entries (older than TTL)
    for (const [reqId, token] of this.processedRequests) {
      const bt = this.tokens.get(token);
      if (!bt) {
        this.processedRequests.delete(reqId);
      }
    }
  }

  private base64URLEncode(bytes: Uint8Array): string {
    // Convert to binary string, then btoa, then make URL-safe
    let binary = "";
    for (let i = 0; i < bytes.length; i++) {
      binary += String.fromCharCode(bytes[i]);
    }
    return btoa(binary)
      .replace(/\+/g, "-")
      .replace(/\//g, "_")
      .replace(/=+$/, "");
  }
}
