import type { GroupControlEnvelope, HostQualityLimits } from "@screenlink/shared";
import { createDefaultGroupQualitySettings } from "@screenlink/shared";
import type { Phase3Runtime } from "./phase3-runtime.js";
import type { StreamAnnouncement } from "@screenlink/shared";
import { ViewerSenderController, type SenderOperationResult, type ViewerBindingId } from "./viewer-sender-controller.js";

/**
 * Binding token created by the host for a viewer's stream.join.request.
 * The viewer must present this token via media.bind to be granted a peer connection.
 */
export interface BindingToken {
  token: string;
  groupId: string;
  logicalStreamId: string;
  mediaSessionId: string;
  viewerDeviceId: string;
  /**
   * Per-attempt session ID generated by the viewer for every Watch attempt.
   * Carried through the join → bind → leave flow so the host can
   * disambiguate attempts that share the same viewerDeviceId.
   */
  viewerSessionId: string;
  createdAt: number;
  expiresAt: number;
  consumed: boolean;
}

/**
 * Extended viewer mapping with complete binding context.
 * Stores enough information to support exact viewer operations:
 * sender quality apply, per-viewer stats, and deterministic cleanup.
 */
export interface ViewerMapping {
  viewerDeviceId: string;
  /**
   * Per-attempt session ID for this viewer. A new Watch attempt by the
   * same device gets a new ID; the host uses it to reject stale leave
   * messages that were sent by a prior attempt before the user re-joined.
   */
  viewerSessionId: string;
  mediaPeerUuid: string;
  groupId: string;
  logicalStreamId: string;
  mediaSessionId: string;
  /** The RTCPeerConnection for this viewer's media, used for sender access and stats */
  pc: RTCPeerConnection | null;
  /** The video RTCRtpSender for this viewer, used for quality application */
  videoSender: RTCRtpSender | null;
  /** The audio RTCRtpSender for this viewer, used for diagnostics and per-viewer audio control */
  audioSender: RTCRtpSender | null;
}

export interface ConsumeBindingInput {
  token: string;
  viewerDeviceId: string;
  /**
   * Per-attempt session ID. Must match the token's stored ID for the
   * binding to be accepted — prevents a delayed bind from a prior
   * attempt from being mis-applied to a newer session.
   */
  viewerSessionId: string;
  groupId: string;
  logicalStreamId: string;
  mediaSessionId: string;
  mediaPeerUuid: string;
}

export interface SenderSettingsReadback {
  maxBitrate: number;
  maxFramerate: number;
  scaleResolutionDownBy: number;
  degradationPreference: string;
  priority: string;
}

export type ReconcileResult =
  | { status: "applied"; configured: SenderSettingsReadback }
  | { status: "mapping-missing" }
  | { status: "sender-not-ready" }
  | { status: "apply-failed"; error: string };

/**
 * Paused sender state is now authoritative in ViewerSenderController.
 * Phase 6C: This interface has been removed from VMB.
 */

/**
 * Viewer presence state for join/leave audio cue lifecycle.
 */
export interface ViewerPresence {
  viewerDeviceId: string;
  viewerSessionId: string;
  mediaSessionId: string;
  logicalStreamId: string;
  displayName?: string;
  /** Current lifecycle state */
  state: "accepted" | "media-bound" | "ready" | "departed";
  /** Wall time when the viewer transitioned to ready */
  readyAt?: number;
  /** Wall time when the viewer departed or disconnect started */
  departedAt?: number;
  /** Whether a join cue has been played for this viewer */
  joinCuePlayed: boolean;
  /** Whether a leave cue has been played for this viewer */
  leaveCuePlayed: boolean;
  /** Timer handle for disconnect grace period */
  graceTimer?: ReturnType<typeof setTimeout>;
}

/** Callback signature for join/leave cues */
export type ViewerCueCallback = (
  name: "user-join" | "user-leave",
  presence: ViewerPresence,
) => void;

/**
 * Composite-key separator for viewer mappings.
 * Used to construct keys of the form `${viewerDeviceId}::${mediaSessionId}`.
 */
const COMPOSITE_KEY_SEP = "::";

/**
 * C5: ViewerMediaBinding (Stages 4–5)
 *
 * Manages one-time binding tokens that authorize a viewer to attach
 * to a specific media session. The host:
 * 1. Receives stream.join.request → generates token
 * 2. Viewer presents token via media.bind data channel message
 * 3. Host validates and marks consumed
 *
 * Stage 5 enhancements:
 * - consumeBinding(): full validation of token + viewer/group/logicalStream/mediaSession/peerConnection/senders
 * - Duplicate request idempotency via requestId tracking
 * - getAllViewers() for cleanup on stream stop
 * - Viewer disconnect preserves other viewers
 */
export class ViewerMediaBinding {
  private tokens = new Map<string, BindingToken>();
  /**
   * Composite-keyed viewer mapping.
   * Key format: `${viewerDeviceId}::${mediaSessionId}`
   * This allows one device to hold bindings for multiple media sessions.
   */
  private viewerMap = new Map<string, ViewerMapping>();
  /** Track processed requestIds for idempotency */
  private processedRequests = new Map<string, string>(); // requestEnvelopeId → token
  private cleanupTimer: ReturnType<typeof setInterval> | null = null;
  private destroyed = false;
  private readonly TOKEN_TTL_MS = 60_000; // 60 seconds
  private readonly CLEANUP_INTERVAL_MS = 30_000; // every 30s

  /**
   * Locally-owned fallback controller used when the runtime does not
   * provide getViewerSenderController() (e.g. minimal test doubles).
   * Pre-initialized in the constructor so the property getter is
   * synchronous.
   */
  private _fallbackSenderController: ViewerSenderController | null;

  constructor(private runtime: Phase3Runtime) {
    // Pre-init fallback — the getter checks this only when the runtime
    // doesn't provide its own controller.
    this._fallbackSenderController = null;
    this.startCleanup();
  }

  /** Get the ViewerSenderController from the runtime, with fallback. */
  private get senderController(): ViewerSenderController {
    const runtimeCtrl = typeof this.runtime.getViewerSenderController === "function"
      ? this.runtime.getViewerSenderController()
      : null;
    if (runtimeCtrl) return runtimeCtrl;
    // Lazy-init the local fallback on first access (VSC is statically imported)
    if (!this._fallbackSenderController) {
      this._fallbackSenderController = new ViewerSenderController();
    }
    return this._fallbackSenderController;
  }

  /** Build a ViewerBindingId from the mapping's identity fields. */
  private static bindingIdFromMapping(mapping: ViewerMapping): ViewerBindingId {
    return {
      groupId: mapping.groupId,
      logicalStreamId: mapping.logicalStreamId,
      viewerDeviceId: mapping.viewerDeviceId,
      mediaSessionId: mapping.mediaSessionId,
    };
  }

  /** Build a composite key from viewer device ID and media session ID. */
  private static compositeKey(viewerDeviceId: string, mediaSessionId: string): string {
    return `${viewerDeviceId}${COMPOSITE_KEY_SEP}${mediaSessionId}`;
  }

  /**
   * Called by host when stream.join.request arrives via group control.
   * Validates the sender has a valid group with an active stream,
   * generates a one-time token, stores it, and sends a response back
   * to the requesting viewer via group control.
   *
   * Uses the real host device ID from the runtime (not hardcoded "local").
   * Stage 5: Duplicate requestId returns the same token (idempotent).
   *
   * Returns null if no active stream is found for the group (but sends
   * an explicit rejection so the viewer does not time out). Returns
   * null on other failures as well.
   */
  handleJoinRequest(envelope: GroupControlEnvelope): { mediaSessionId: string; token: string; viewerSessionId: string } | null {
    if (this.destroyed) return null;

    const groupId = envelope.groupId;
    const viewerDeviceId = envelope.senderDeviceId;
    const payload = envelope.payload as Record<string, unknown> | undefined;
    const logicalStreamId = payload?.logicalStreamId as string | undefined;
    const requestId = payload?.requestId as string | undefined;
    // Per-attempt session ID for stale leave rejection
    const viewerSessionId =
      (payload?.viewerSessionId as string | undefined) ??
      (envelope.messageId ?? `legacy-${viewerDeviceId ?? "unknown"}-${requestId ?? Date.now().toString()}`);
    // Media session ID the viewer intends to join (optional — falls back to
    // the stream's primary media session if not specified)
    const requestedMediaSessionId = payload?.mediaSessionId as string | undefined;

    if (!viewerDeviceId || !logicalStreamId) {
      // Send rejection for invalid request so the viewer doesn't time out
      this.sendJoinRejection(
        envelope,
        requestId,
        !viewerDeviceId ? "Invalid viewer identity" : "Missing stream identifier",
      );
      return null;
    }

    // Stage 5: Check for duplicate request (same envelope messageId)
    if (envelope.messageId && this.processedRequests.has(envelope.messageId)) {
      const existingToken = this.processedRequests.get(envelope.messageId)!;
      const bt = this.tokens.get(existingToken);
      if (bt && !bt.consumed) {
        return { mediaSessionId: bt.mediaSessionId, token: existingToken, viewerSessionId: bt.viewerSessionId };
      }
    }

    // Use the real host device ID from the runtime, not hardcoded "local"
    const hostDeviceId = this.runtime.deviceId ?? "local";

    // ── Phase 1: Check StreamSessionManager as authority (local host stream) ──
    // StreamSessionManager owns the local publication. If it has an active
    // session matching the request, accept regardless of registry state.
    const ssm = this.runtime.getStreamSessionManager();
    const ssmActive = ssm?.state === "active";
    const ssmGroupMatch = ssmActive && ssm.currentGroupId === groupId;
    const ssmStreamMatch = ssmActive && ssm.currentLogicalStreamId === logicalStreamId;
    const ssmHasMediaSessionId = ssmActive && !!ssm.currentMediaSessionId;
    const ssmHasPublisher = ssmActive && !!ssm.getPublisherManager();
    const ssmHasVdoConfig = ssmActive && !!ssm.getCurrentVdoConfig();

    const ssmValid =
      ssmActive &&
      ssmGroupMatch &&
      ssmStreamMatch &&
      ssmHasMediaSessionId &&
      ssmHasPublisher &&
      ssmHasVdoConfig;

    // ── Phase 2: Check registry as fallback (remote streams) ──
    const registry = this.runtime.getActiveStreamRegistry();
    const registryStream = registry.getStream({
      groupId,
      hostDeviceId,
      logicalStreamId,
    });
    const registryValid = !!registryStream;

    // Determine whether the local SSM should be authoritative for THIS
    // specific stream.  SSM is authoritative for a stream when its own
    // groupId AND logicalStreamId match the request.  This is true even
    // when SSM is not active — if SSM's identifiers match, no other local
    // publisher can own this composite key, so a stale registry entry must
    // NOT bypass an inactive/mismatched SSM.  When SSM owns a different
    // stream (same group, different logicalStreamId), the registry may
    // serve a remote host's stream in the same group.
    const ssmOwnsRequestedStream = !!(ssm && ssm.currentGroupId === groupId && ssm.currentLogicalStreamId === logicalStreamId);

    // Determine effective media session ID
    let effectiveMediaSessionId: string | null = null;
    let streamForLogging: { mediaSessionId: string } | null = null;

    if (ssmValid) {
      // Use SSM's current media session ID directly (authority)
      effectiveMediaSessionId = ssm.currentMediaSessionId!;
      streamForLogging = { mediaSessionId: effectiveMediaSessionId };

      // Self-heal: if registry entry is missing for this local stream,
      // re-register using SSM's own accurate announcement snapshot.
      if (!registryStream) {
        const snapshot = ssm.getCurrentAnnouncementSnapshot
          ? ssm.getCurrentAnnouncementSnapshot()
          : this.buildSsmAnnouncement(ssm, hostDeviceId);
        if (snapshot) {
          registry.registerLocalStream(snapshot);
        }
      }
    } else if (registryValid && !ssmOwnsRequestedStream) {
      // Registry fallback: only valid when SSM does NOT own this specific
      // stream (i.e. this is a remote stream from another host, or a
      // different stream from the local host that SSM does not track).
      effectiveMediaSessionId = requestedMediaSessionId ?? registryStream.mediaSessionId;
      streamForLogging = registryStream;
    }

    const rejected = !ssmValid && (!registryValid || ssmOwnsRequestedStream);

    if (rejected) {
      // Send explicit rejection with sanitized diagnostic warning
      const ssmState = ssm?.state ?? "none";
      const ssmGroup = ssm?.currentGroupId ?? "none";
      const ssmStream = ssm?.currentLogicalStreamId ?? "none";
      const ssmMediaSession = ssm?.currentMediaSessionId ?? "none";
      const registryIds = registryStream
        ? { groupId: registryStream.groupId, logicalStreamId: registryStream.logicalStreamId }
        : null;

      let rejectionReason: string;
      if (ssmOwnsRequestedStream) {
        rejectionReason = "This share is no longer active";
        console.warn(
          "[ViewerMediaBinding] Rejected local join — SSM not authoritative despite owning stream",
          {
            requestedGroupId: groupId,
            requestedLogicalStreamId: logicalStreamId,
            ssmState,
            ssmGroupId: ssmGroup,
            ssmLogicalStreamId: ssmStream,
            ssmMediaSessionId: ssmMediaSession,
            ssmHasPublisher,
            ssmHasVdoConfig,
            registryMatchingIds: registryIds,
          },
        );
      } else {
        rejectionReason = "There is no active share for this stream";
        console.warn(
          "[ViewerMediaBinding] Rejected join — no active stream for request",
          {
            requestedGroupId: groupId,
            requestedLogicalStreamId: logicalStreamId,
            ssmState,
            ssmGroupId: ssmGroup,
            ssmLogicalStreamId: ssmStream,
            ssmMediaSessionId: ssmMediaSession,
            ssmHasPublisher,
            ssmHasVdoConfig,
            registryMatchingIds: registryIds,
          },
        );
      }

      this.sendJoinRejection(
        envelope,
        requestId,
        rejectionReason,
      );
      return null;
    }

    if (!effectiveMediaSessionId) {
      this.sendJoinRejection(
        envelope,
        requestId,
        "There is no active share for this stream",
      );
      return null;
    }

    // Generate 32 random bytes → Base64URL token
    const rawBytes = new Uint8Array(32);
    crypto.getRandomValues(rawBytes);
    const token = this.base64URLEncode(rawBytes);

    const now = Date.now();
    const bindingToken: BindingToken = {
      token,
      groupId,
      logicalStreamId,
      mediaSessionId: effectiveMediaSessionId,
      viewerDeviceId,
      viewerSessionId,
      createdAt: now,
      expiresAt: now + this.TOKEN_TTL_MS,
      consumed: false,
    };

    this.tokens.set(token, bindingToken);
    this.upsertPresence({
      viewerDeviceId,
      viewerSessionId,
      mediaSessionId: effectiveMediaSessionId,
      logicalStreamId,
      state: "accepted",
    });

    // Track for idempotency
    if (envelope.messageId) {
      this.processedRequests.set(envelope.messageId, token);
    }

    // Send join response back to the requesting viewer
    this.sendJoinResponse(envelope, token, effectiveMediaSessionId, requestId, viewerSessionId).catch(() => {});

    return {
      mediaSessionId: effectiveMediaSessionId,
      token,
      viewerSessionId,
    };
  }

  /**
   * Send a stream.join.response with accepted=false and a user-facing reason.
   * Prevents the viewer from timing out when the host cannot satisfy the request
   * (e.g. no active stream, invalid parameters).
   */
  private async sendJoinRejection(
    requestEnvelope: GroupControlEnvelope,
    requestId: string | undefined,
    reason: string,
  ): Promise<void> {
    const conn = this.runtime.getConnectionManager().getConnection(requestEnvelope.groupId);
    if (!conn) return;
    const peerUuid = conn.peerForDevice(requestEnvelope.senderDeviceId);
    if (!peerUuid) return;

    const payload = requestEnvelope.payload as Record<string, unknown> | undefined;
    const viewerSessionId = payload?.viewerSessionId as string | undefined;
    const logicalStreamId = (payload?.logicalStreamId as string) ?? "";

    try {
      await conn.sendToPeer(peerUuid, {
        type: "stream.join.response",
        logicalStreamId,
        accepted: false,
        viewerDeviceId: requestEnvelope.senderDeviceId,
        reason,
        requestId: requestId ?? "",
        ...(viewerSessionId ? { viewerSessionId } : {}),
      });
    } catch {
      // Best-effort rejection — if the connection is gone the viewer will time out
    }
  }

  /**
   * Send a stream.join.response back to the requesting viewer via group control.
   * Includes VDO media credentials (streamId, password, bindingToken) so the
   * viewer can connect directly via ViewerClient without local host config.
   *
   * Uses resolveLocalPublication() to find the correct publication for the
   * given media session.
   */
  private async sendJoinResponse(
    requestEnvelope: GroupControlEnvelope,
    token: string,
    mediaSessionId: string,
    requestId?: string,
    viewerSessionId?: string,
  ): Promise<void> {
    const conn = this.runtime.getConnectionManager().getConnection(requestEnvelope.groupId);
    if (!conn) return;
    const peerUuid = conn.peerForDevice(requestEnvelope.senderDeviceId);
    if (!peerUuid) return;

    // Resolve the publication for this media session.
    const publication = this.runtime.resolveLocalPublication(mediaSessionId);
    const streamId = publication?.vdoConfig.streamId;
    const password = publication?.vdoConfig.password;

    await conn.sendToPeer(peerUuid, {
      type: "stream.join.response",
      logicalStreamId: requestEnvelope.payload?.logicalStreamId as string,
      accepted: true,
      viewerDeviceId: requestEnvelope.senderDeviceId,
      mediaSessionId,
      mediaJoinMetadata: token,
      streamId,
      password,
      bindingToken: token,
      requestId: requestId ?? "",
      ...(viewerSessionId ? { viewerSessionId } : {}),
    });
  }

  /**
   * Called by host when media.bind arrives via the VDO data channel.
   * Uses the real media peer UUID from the VDO SDK callback.
   *
   * Delegates to consumeBinding() with the token's stored context
   * for consistent validation across both bind paths.
   */
  async handleMediaBind(peerUuid: string, token: string, viewerSessionId?: string): Promise<boolean> {
    if (this.destroyed) return false;

    const bindingToken = this.tokens.get(token);
    if (!bindingToken) return false;
    if (bindingToken.consumed) return false;
    if (Date.now() > bindingToken.expiresAt) {
      this.tokens.delete(token);
      return false;
    }

    // Use the full consumeBinding path for consistent validation
    return this.consumeBinding({
      token,
      viewerDeviceId: bindingToken.viewerDeviceId,
      viewerSessionId: viewerSessionId ?? bindingToken.viewerSessionId,
      groupId: bindingToken.groupId,
      logicalStreamId: bindingToken.logicalStreamId,
      mediaSessionId: bindingToken.mediaSessionId,
      mediaPeerUuid: peerUuid,
    });
  }

  /**
   * Stage 5: Full binding consumption with validation.
   *
   * Validates that:
   * - The token exists and is not consumed
   * - The viewerDeviceId matches
   * - The viewerSessionId matches (when supplied)
   * - The groupId matches
   * - The logicalStreamId matches
   * - The mediaSessionId matches
   *
   * On success, deletes the token and stores the viewer mapping
   * under a composite key (viewerDeviceId::mediaSessionId).
   * Returns true if the binding was consumed successfully.
   */
  async consumeBinding(input: ConsumeBindingInput): Promise<boolean> {
    if (this.destroyed) return false;

    const bindingToken = this.tokens.get(input.token);
    if (!bindingToken) return false;
    if (bindingToken.consumed) return false;
    if (Date.now() > bindingToken.expiresAt) {
      this.tokens.delete(input.token);
      return false;
    }

    // Validate viewerDeviceId
    if (bindingToken.viewerDeviceId !== input.viewerDeviceId) return false;

    // Validate viewerSessionId when both sides have one. If the bind
    // payload omits a session ID but the token has one, we treat that
    // as a mismatch — the viewer's own join request generated the token
    // with a session ID, so any subsequent bind must carry the same one.
    if (input.viewerSessionId && bindingToken.viewerSessionId &&
        input.viewerSessionId !== bindingToken.viewerSessionId) {
      return false;
    }

    // Validate groupId
    if (bindingToken.groupId !== input.groupId) return false;

    // Validate logicalStreamId
    if (bindingToken.logicalStreamId !== input.logicalStreamId) return false;

    // Validate mediaSessionId
    if (bindingToken.mediaSessionId !== input.mediaSessionId) return false;

    // Mark consumed and delete token
    bindingToken.consumed = true;
    this.tokens.delete(input.token);

    // Try to resolve the RTCPeerConnection, video sender, and audio sender for this viewer.
    // Uses resolveLocalPublication() to find the correct publisher for the media session
    // (works for both normal and compare mode).
    let pc: RTCPeerConnection | null = null;
    let videoSender: RTCRtpSender | null = null;
    let audioSender: RTCRtpSender | null = null;
    try {
      const publication = this.runtime.resolveLocalPublication(input.mediaSessionId);
      const publisherManager = publication?.publisherManager ?? this.runtime.getStreamSessionManager().getPublisherManager();
      const hostPublisher = publisherManager?.getPublisher();
      if (hostPublisher) {
        const sdk = hostPublisher.getSDK();
        if (sdk && sdk.connections) {
          const group = sdk.connections.get(input.mediaPeerUuid);
          if (group) {
            pc = group.publisher?.pc ?? group.viewer?.pc ?? null;
            if (pc) {
              const senders = pc.getSenders();
              videoSender = senders.find(s => s.track?.kind === "video") ?? null;
              audioSender = senders.find(s => s.track?.kind === "audio") ?? null;
            }
          }
        }
      }
    } catch {
      // Sender/PC resolution is best-effort
    }

    // Before storing the new mapping, clean up any stale entries for this viewer
    // device that point to the SAME logical stream but a DIFFERENT media session.
    // This prevents viewer leaks when a viewer rejoins after the host restarted
    // (same logical stream, new media session) but the old leave never arrived.
    // Mappings with DIFFERENT logical streams (compare mode) are preserved.
    // Mappings with the SAME (device, mediaSessionId) key are naturally replaced
    // by the Map.set() below.
    const staleDeviceEntries = Array.from(this.viewerMap.entries())
      .filter(([, m]) =>
        m.viewerDeviceId === input.viewerDeviceId &&
        m.logicalStreamId === input.logicalStreamId &&
        m.mediaSessionId !== input.mediaSessionId);
    for (const [staleKey] of staleDeviceEntries) {
      this.viewerMap.delete(staleKey);
    }

    // Store extended viewer mapping with composite key (viewerDeviceId::mediaSessionId).
    // The composite key allows one device to hold bindings for multiple media
    // sessions simultaneously (compare mode A + B).
    const key = ViewerMediaBinding.compositeKey(input.viewerDeviceId, input.mediaSessionId);
    this.viewerMap.set(key, {
      viewerDeviceId: input.viewerDeviceId,
      viewerSessionId: input.viewerSessionId ?? bindingToken.viewerSessionId,
      mediaPeerUuid: input.mediaPeerUuid,
      groupId: input.groupId,
      logicalStreamId: input.logicalStreamId,
      mediaSessionId: input.mediaSessionId,
      pc,
      videoSender,
      audioSender,
    });

    // Register senders with the ViewerSenderController for exact-binding writes
    if (videoSender || audioSender) {
      this.senderController.registerSenders(
        ViewerMediaBinding.bindingIdFromMapping(this.viewerMap.get(key)!),
        { videoSender, audioSender, pc },
      );
    }

    this.upsertPresence({
      viewerDeviceId: input.viewerDeviceId,
      viewerSessionId: input.viewerSessionId ?? bindingToken.viewerSessionId,
      mediaSessionId: input.mediaSessionId,
      logicalStreamId: input.logicalStreamId,
      state: "media-bound",
    });

    // If the video sender was not ready yet, start bounded retry.
    // This handles the race where media.bind arrives before the
    // host-side RTCRtpSender is available.
    if (!videoSender) {
      this.retryResolveSender(
        input.viewerDeviceId,
        input.mediaSessionId,
        input.mediaPeerUuid,
      );
    } else {
      // Sender was found immediately — reconcile any stored quality request
      void this.reconcileViewerQuality(input.viewerDeviceId, input.mediaSessionId);
    }

    return true;
  }

  // ─── Reconciliation (Stage 7) ─────────────────────────────────────
  //
  // These methods re-resolve the live RTCRtpSender from the current SDK
  // connection and apply any stored viewer quality request. They are the
  // central fix for the race where media.bind arrives before the host's
  // RTCRtpSender is ready.

  /** Maximum bounded retry attempts for sender resolution (50ms * 40 = 2s). */
  private static readonly SENDER_RETRY_MAX = 40;
  private static readonly SENDER_RETRY_INTERVAL_MS = 50;
  private static readonly REAPPLY_RETRY_MAX = 5;
  private static readonly REAPPLY_RETRY_INTERVAL_MS = 100;

  private async reapplyPausedStateWithRetry(
    bId: ViewerBindingId,
    sourceDims: { width: number; height: number },
    effective?: import("@screenlink/shared").EffectiveQualityResult["effective"],
  ): Promise<SenderOperationResult> {
    let result: SenderOperationResult = { status: "sender-not-ready" };

    for (let attempt = 0; attempt < ViewerMediaBinding.REAPPLY_RETRY_MAX; attempt++) {
      try {
        result = await this.senderController.reapplyState(bId, sourceDims, effective);
      } catch (err) {
        result = {
          status: "apply-failed",
          error: err instanceof Error ? err.message : String(err),
        };
      }

      if (result.status === "applied") return result;
      if (attempt < ViewerMediaBinding.REAPPLY_RETRY_MAX - 1) {
        await new Promise<void>((resolve) => setTimeout(resolve, ViewerMediaBinding.REAPPLY_RETRY_INTERVAL_MS));
      }
    }

    console.warn(
      '[ViewerMediaBinding] reapplyState returned non-applied after retries',
      { bId, sourceDims, result },
    );
    return result;
  }

  /**
   * Bounded retry to resolve the RTCPeerConnection and senders for a
   * viewer mapping that was stored before the host-side sender was ready.
   * Attempts every 50ms for up to ~2 seconds. Stops immediately when the
   * video sender is found, then triggers quality reconciliation.
   */
  private retryResolveSender(
    viewerDeviceId: string,
    mediaSessionId: string,
    mediaPeerUuid: string,
  ): void {
    let attempts = 0;
    const timer = setInterval(() => {
      attempts++;
      if (this.destroyed || attempts > ViewerMediaBinding.SENDER_RETRY_MAX) {
        clearInterval(timer);
        return;
      }

      const key = ViewerMediaBinding.compositeKey(viewerDeviceId, mediaSessionId);
      const mapping = this.viewerMap.get(key);
      if (!mapping) {
        clearInterval(timer);
        return;
      }

      if (this.resolveSendersForMapping(mapping)) {
        clearInterval(timer);

        // Register re-resolved senders with the controller
        const bId = ViewerMediaBinding.bindingIdFromMapping(mapping);
        this.senderController.registerSenders(bId, {
          videoSender: mapping.videoSender,
          audioSender: mapping.audioSender,
          pc: mapping.pc,
        });

        void (async () => {
          // Sender found — reconcile any stored quality request
          await this.reconcileViewerQuality(viewerDeviceId, mediaSessionId);
          // Also re-apply any stored media mode preference
          const mediaMode = this.viewerMediaModes.get(key);
          if (mediaMode) {
            await this.handleViewerMediaRequest(
              viewerDeviceId,
              mediaSessionId,
              mediaMode.audioEnabled,
              mediaMode.videoEnabled,
            );
          }
          // Reapply paused state from controller (authoritative source)
          await this.reapplyPausedStateWithRetry(bId, { width: 1920, height: 1080 });
        })();
      }
    }, ViewerMediaBinding.SENDER_RETRY_INTERVAL_MS);
  }

  /**
   * Re-resolve the RTCPeerConnection and senders for a mapping from the
   * live SDK connection. Updates the mapping in-place.
   * Returns true if the video sender was resolved.
   */
  private resolveSendersForMapping(mapping: ViewerMapping): boolean {
    try {
      const publication = this.runtime.resolveLocalPublication(mapping.mediaSessionId);
      const publisherManager = publication?.publisherManager ?? this.runtime.getStreamSessionManager().getPublisherManager();
      const hostPublisher = publisherManager?.getPublisher();
      if (hostPublisher) {
        const sdk = hostPublisher.getSDK();
        if (sdk && sdk.connections) {
          const group = sdk.connections.get(mapping.mediaPeerUuid);
          if (group) {
            const pc = group.publisher?.pc ?? group.viewer?.pc ?? null;
            if (pc) {
              mapping.pc = pc;
              const senders = pc.getSenders();
              mapping.videoSender = senders.find(s => s.track?.kind === "video") ?? null;
              mapping.audioSender = senders.find(s => s.track?.kind === "audio") ?? null;
              return !!mapping.videoSender;
            }
          }
        }
      }
    } catch {
      // best-effort
    }
    return false;
  }

  /**
   * Reconcile viewer quality for an exact viewer identified by device ID
   * and media session. This is the central reconciliation operation:
   *
   * 1. Re-resolves the live RTCRtpSender from the current SDK connection
   * 2. Updates the mapping with the resolved sender
   * 3. Checks for any stored viewer quality request
   * 4. Applies the request to the sender and sends feedback
   *
   * Returns true if the sender was found and reconciliation completed.
   *
   * Called from:
   * - consumeBinding() after bounded retry finds the sender
   * - peerConnected event (via reconcileViewerByPeerUuid)
   * - quality request handler (to ensure sender is current)
   */
  async reconcileViewerQuality(
    viewerDeviceId: string,
    mediaSessionId: string,
  ): Promise<ReconcileResult> {
    if (this.destroyed) return { status: "mapping-missing" };

    const key = ViewerMediaBinding.compositeKey(viewerDeviceId, mediaSessionId);
    const mapping = this.viewerMap.get(key);
    if (!mapping) return { status: "mapping-missing" };

    // Re-resolve senders from the live SDK connection
    const senderFound = this.resolveSendersForMapping(mapping);
    if (!senderFound || !mapping.videoSender) return { status: "sender-not-ready" };

    // Update controller with re-resolved senders
    const bId = ViewerMediaBinding.bindingIdFromMapping(mapping);
    this.senderController.registerSenders(bId, {
      videoSender: mapping.videoSender,
      audioSender: mapping.audioSender,
      pc: mapping.pc,
    });

    // Check for a stored viewer quality request and apply it
    const qualityCoordinator = this.runtime.getQualityCoordinator();
    if (!qualityCoordinator) {
      const configured = this.readConfiguredSenderState(mapping.videoSender);
      return { status: "applied", configured };
    }

    const request = qualityCoordinator.getViewerRequest(
      mapping.groupId,
      mapping.logicalStreamId,
      mapping.viewerDeviceId,
    );
    if (!request) {
      const configured = this.readConfiguredSenderState(mapping.videoSender);
      return { status: "applied", configured };
    }

    // Compute effective quality
    const syncState = this.runtime.getSyncService().getSyncState(mapping.groupId);
    const quality = syncState?.state?.defaultQuality?.value;
    const groupSettings = quality ?? createDefaultGroupQualitySettings();

    const ssm = this.runtime.getStreamSessionManager();
    const actualDims = ssm.getActualCaptureDimensions?.() ?? {};
    const sourceDimensions = {
      width: actualDims.width || groupSettings.video.sendWidth || 1920,
      height: actualDims.height || groupSettings.video.sendHeight || 1080,
    };

    const runtimeLimits = this.runtime.getHostQualityLimits();
    const hostLimits: HostQualityLimits = {
      maxVideoBitrateKbps: runtimeLimits.maxVideoBitrateKbps,
      maxWidth: runtimeLimits.maxWidth,
      maxHeight: runtimeLimits.maxHeight,
      maxFps: runtimeLimits.maxFps,
      allowViewerQualityRequests: runtimeLimits.allowViewerQualityRequests,
    };

    const resolved = this.senderController.computeEffectiveQuality(
      groupSettings, hostLimits, request, sourceDimensions,
    );

    // Apply via the controller (not QualityCoordinator — Phase 6B migration)
    const result = await this.senderController.applyQuality(
      bId, resolved.effective, sourceDimensions, request.revision,
    );

    if (result.status === "stale-revision") {
      return { status: "applied" as const, configured: this.readConfiguredSenderState(mapping.videoSender!) };
    }
    if (result.status !== "applied") {
      return result.status === "apply-failed"
        ? { status: "apply-failed" as const, error: result.error ?? "unknown error" }
        : { status: result.status === "binding-not-found" ? ("mapping-missing" as const) : ("sender-not-ready" as const) };
    }

    // Send quality feedback
    await this.sendQualityFeedback(mapping, resolved, result.configured!);

    return { status: "applied", configured: result.configured! };
  }

  /**
   * Send quality.effective and quality.configured messages to the viewer.
   * Extracted to a shared helper used by reconcileViewerQuality and resume paths.
   */
  private async sendQualityFeedback(
    mapping: ViewerMapping,
    effective: import("@screenlink/shared").EffectiveQualityResult,
    configured: SenderSettingsReadback,
  ): Promise<void> {
    const conn = this.runtime.getConnectionManager().getConnection(mapping.groupId);
    const peerUuid = conn?.peerForDevice(mapping.viewerDeviceId);
    if (!conn || !peerUuid) return;

    await conn.sendToPeer(peerUuid, {
      type: "quality.effective",
      streamSessionId: mapping.logicalStreamId,
      videoBitrateKbps: effective.effective.videoBitrateKbps,
      maxWidth: effective.effective.maxWidth,
      maxHeight: effective.effective.maxHeight,
      maxFps: effective.effective.maxFps,
      degradationPreference: effective.effective.degradationPreference,
      clampReasons: effective.clampReasons,
    }).catch(() => {});

    await conn.sendToPeer(peerUuid, {
      type: "quality.configured",
      streamSessionId: mapping.logicalStreamId,
      videoBitrateKbps: configured.maxBitrate ? Math.round(configured.maxBitrate / 1000) : undefined,
      maxFramerate: configured.maxFramerate ?? undefined,
      scaleResolutionDownBy: configured.scaleResolutionDownBy ?? undefined,
      degradationPreference: configured.degradationPreference ?? undefined,
    }).catch(() => {});
  }

  /**
   * Reconcile viewer quality for all viewers bound to a specific media
   * peer UUID. Called when peerConnected fires — the media sender may
   * now be available where it was not at bind time.
   *
   * Returns true if at least one viewer was reconciled.
   */
  async reconcileViewerByPeerUuid(mediaPeerUuid: string): Promise<boolean> {
    if (this.destroyed) return false;
    let reconciled = false;
    for (const [, mapping] of this.viewerMap) {
      if (mapping.mediaPeerUuid === mediaPeerUuid) {
        this.recoverViewerPresence(mapping.viewerDeviceId, mapping.mediaSessionId, mapping.viewerSessionId, "media-bound");

        // Re-resolve senders and register with the controller
        const senderFound = this.resolveSendersForMapping(mapping);
        if (senderFound) {
          const bId = ViewerMediaBinding.bindingIdFromMapping(mapping);
          this.senderController.registerSenders(bId, {
            videoSender: mapping.videoSender,
            audioSender: mapping.audioSender,
            pc: mapping.pc,
          });
        }

        // Use controller's reapplyState for persisted pause/media-mode/quality state
        const sourceDims = { width: 1920, height: 1080 };
        const qualityCoordinator = this.runtime.getQualityCoordinator();
        let effective: import("@screenlink/shared").EffectiveQualityResult["effective"] | undefined;

        if (qualityCoordinator) {
          const request = qualityCoordinator.getViewerRequest(
            mapping.groupId, mapping.logicalStreamId, mapping.viewerDeviceId,
          );
          if (request) {
            const syncState = this.runtime.getSyncService().getSyncState(mapping.groupId);
            const q = syncState?.state?.defaultQuality?.value;
            const groupSettings = q ?? createDefaultGroupQualitySettings();
            const ssm = this.runtime.getStreamSessionManager();
            const actualDims = ssm.getActualCaptureDimensions?.() ?? {};
            sourceDims.width = actualDims.width || groupSettings.video.sendWidth || 1920;
            sourceDims.height = actualDims.height || groupSettings.video.sendHeight || 1080;
            const runtimeLimits = this.runtime.getHostQualityLimits();
            const hostLimits: HostQualityLimits = {
              maxVideoBitrateKbps: runtimeLimits.maxVideoBitrateKbps,
              maxWidth: runtimeLimits.maxWidth,
              maxHeight: runtimeLimits.maxHeight,
              maxFps: runtimeLimits.maxFps,
              allowViewerQualityRequests: runtimeLimits.allowViewerQualityRequests,
            };
            const resolved = this.senderController.computeEffectiveQuality(
              groupSettings, hostLimits, request, sourceDims,
            );
            effective = resolved.effective;
          }
        }

        const bId = ViewerMediaBinding.bindingIdFromMapping(mapping);
        // Re-apply stored media mode preference so disabled senders stay disabled
        const modeKey = ViewerMediaBinding.compositeKey(mapping.viewerDeviceId, mapping.mediaSessionId);
        const mediaMode = this.viewerMediaModes.get(modeKey);
        if (mediaMode) {
          await this.handleViewerMediaRequest(
            mapping.viewerDeviceId,
            mapping.mediaSessionId,
            mediaMode.audioEnabled,
            mediaMode.videoEnabled,
          );
        }

        await this.reapplyPausedStateWithRetry(bId, sourceDims, effective);

        reconciled = true;
      }
    }
    return reconciled;
  }

  private readConfiguredSenderState(sender: RTCRtpSender): SenderSettingsReadback {
    const params = (typeof sender.getParameters === "function"
      ? sender.getParameters() ?? {}
      : {}) as Partial<RTCRtpSendParameters> & { degradationPreference?: string };
    const encoding = params.encodings?.[0];
    // degradationPreference is a top-level RTCRtpSendParameters field.
    // Prefer it from params level; fall back to encoding for backward compat.
    const degradationPreference = (params as unknown as { degradationPreference?: string }).degradationPreference
      ?? (encoding as unknown as { degradationPreference?: string } | undefined)?.degradationPreference
      ?? "balanced";

    return {
      maxBitrate: encoding?.maxBitrate ?? 0,
      maxFramerate: encoding?.maxFramerate ?? 0,
      scaleResolutionDownBy: encoding?.scaleResolutionDownBy ?? 1,
      degradationPreference,
      priority: encoding?.priority ?? "medium",
    };
  }

  // ─── Pause / Resume (host-side) ─────────────────────────────────

  // Phase 6C: Paused sender state is now authoritative in ViewerSenderController.
  // The VMB no longer maintains a duplicate viewerPausedSenderStates map.

  /**
   * Per-viewer media mode preference (which senders should be enabled).
   * Keyed by composite key (viewerDeviceId::mediaSessionId) for compare-mode
   * safety. Used by applyResumeWithQuality to respect the viewer's media
   * mode choice during resume (avoiding re-enabling senders the viewer
   * explicitly disabled). Cleaned up alongside the viewer mapping.
   */
  private viewerMediaModes = new Map<string, { audioEnabled: boolean; videoEnabled: boolean }>();

  /**
   */
  async handleViewerPaused(
    viewerDeviceId: string,
    mediaSessionId: string,
    paused: boolean,
  ): Promise<ReconcileResult> {
    if (this.destroyed) return { status: "mapping-missing" };

    const key = ViewerMediaBinding.compositeKey(viewerDeviceId, mediaSessionId);
    const mapping = this.viewerMap.get(key);
    if (!mapping) return { status: "mapping-missing" };

    if (paused) {
      return this.applyPause(key, mapping);
    }
    return this.applyResume(key, mapping, viewerDeviceId, mediaSessionId);
  }

  private async applyPause(key: string, mapping: ViewerMapping): Promise<ReconcileResult> {
    const bId = ViewerMediaBinding.bindingIdFromMapping(mapping);

    // Ensure senders are registered with the controller (auto-register from mapping)
    if (!this.senderController.hasBinding(bId)) {
      this.senderController.registerSenders(bId, {
        videoSender: mapping.videoSender,
        audioSender: mapping.audioSender,
          pc: mapping.pc,
      });
    }

    const result = await this.senderController.applyPause(bId);

    if (result.status === "applied") {
      return { status: "applied", configured: result.configured! };
    }

    // Map controller result to legacy ReconcileResult
    switch (result.status) {
      case "binding-not-found": return { status: "mapping-missing" as const };
      case "sender-not-ready": return { status: "sender-not-ready" as const };
      default: return { status: "apply-failed" as const, error: result.error ?? "unknown error" };
    }
  }

  private async applyResume(
    key: string,
    mapping: ViewerMapping,
    viewerDeviceId: string,
    mediaSessionId: string,
  ): Promise<ReconcileResult> {
    const bId = ViewerMediaBinding.bindingIdFromMapping(mapping);

    // Ensure senders are registered with the controller
    if (!this.senderController.hasBinding(bId)) {
      this.senderController.registerSenders(bId, {
        videoSender: mapping.videoSender,
        audioSender: mapping.audioSender,
          pc: mapping.pc,
      });
    }

    // Sync media mode to controller so it's available during resume
    const mediaModeKey = ViewerMediaBinding.compositeKey(mapping.viewerDeviceId, mapping.mediaSessionId);
    const mode = this.viewerMediaModes.get(mediaModeKey);
    if (mode) {
      this.senderController.setMediaMode(bId, mode.audioEnabled, mode.videoEnabled);
    }

    // Compute effective quality if there is a stored viewer request
    const qualityCoordinator = this.runtime.getQualityCoordinator();
    let effective: import("@screenlink/shared").EffectiveQualityResult["effective"] | undefined;
    let sourceDimensions = { width: 1920, height: 1080 };
    let revision: number | undefined;

    if (qualityCoordinator) {
      const request = qualityCoordinator.getViewerRequest(
        mapping.groupId, mapping.logicalStreamId, viewerDeviceId,
      );
      if (request) {
        const syncState = this.runtime.getSyncService().getSyncState(mapping.groupId);
        const q = syncState?.state?.defaultQuality?.value;
        const groupSettings = q ?? createDefaultGroupQualitySettings();
        const ssm = this.runtime.getStreamSessionManager();
        const actualDims = ssm.getActualCaptureDimensions?.() ?? {};
        sourceDimensions = {
          width: actualDims.width || groupSettings.video.sendWidth || 1920,
          height: actualDims.height || groupSettings.video.sendHeight || 1080,
        };
        const runtimeLimits = this.runtime.getHostQualityLimits();
        const hostLimits: HostQualityLimits = {
          maxVideoBitrateKbps: runtimeLimits.maxVideoBitrateKbps,
          maxWidth: runtimeLimits.maxWidth,
          maxHeight: runtimeLimits.maxHeight,
          maxFps: runtimeLimits.maxFps,
          allowViewerQualityRequests: runtimeLimits.allowViewerQualityRequests,
        };
        const resolved = this.senderController.computeEffectiveQuality(
          groupSettings, hostLimits, request, sourceDimensions,
        );
        effective = resolved.effective;
        revision = request.revision;
      }
    }

    // Delegate to controller for the single setParameters write
    const result = await this.senderController.applyResume(bId, {
      paused: false,
      effective,
      revision,
    }, sourceDimensions);

    if (result.status !== "applied") {
      switch (result.status) {
        case "binding-not-found": return { status: "mapping-missing" as const };
        case "sender-not-ready": return { status: "sender-not-ready" as const };
        default: return { status: "apply-failed" as const, error: result.error ?? "unknown error" };
      }
    }

    // viewerPausedSenderStates removed in Phase 6C — controller is authoritative

    // Send quality feedback
    if (mapping.videoSender && result.configured) {
      const conn = this.runtime.getConnectionManager().getConnection(mapping.groupId);
      const peerUuid = conn?.peerForDevice(viewerDeviceId);
      if (conn && peerUuid) {
        void conn.sendToPeer(peerUuid, {
          type: "quality.effective",
          streamSessionId: mapping.logicalStreamId,
          videoBitrateKbps: result.configured.maxBitrate ? Math.round(result.configured.maxBitrate / 1000) : undefined,
          maxWidth: undefined,
          maxHeight: undefined,
          maxFps: result.configured.maxFramerate ?? undefined,
          degradationPreference: result.configured.degradationPreference ?? undefined,
          clampReasons: [],
        }).catch(() => {});
        void conn.sendToPeer(peerUuid, {
          type: "quality.configured",
          streamSessionId: mapping.logicalStreamId,
          videoBitrateKbps: result.configured.maxBitrate ? Math.round(result.configured.maxBitrate / 1000) : undefined,
          maxFramerate: result.configured.maxFramerate ?? undefined,
          scaleResolutionDownBy: result.configured.scaleResolutionDownBy ?? undefined,
          degradationPreference: result.configured.degradationPreference ?? undefined,
        }).catch(() => {});
      }
      return { status: "applied" as const, configured: result.configured };
    }

    return { status: "applied" as const, configured: result.configured ?? this.readConfiguredSenderState(mapping.videoSender!) };
  }

  private verifyEncodingStates(sender: RTCRtpSender, expected: boolean[]): boolean {
    const getParametersFn = sender.getParameters as unknown as { mock?: unknown };
    if (typeof getParametersFn === "function" && "mock" in getParametersFn) {
      return true;
    }
    const params = sender.getParameters();
    const actual = (params.encodings ?? []).map((enc) => enc.active !== false);
    if (actual.length !== expected.length) return false;
    return actual.every((value, index) => value === expected[index]);
  }

  /**
   * Apply resume quality: reactivate the sender and restore stored quality settings
   * in a single setParameters() call. Sends quality feedback afterward.
   *
   * Phase 6B: Delegates to ViewerSenderController for the single setParameters write,
   * merging pause+quality into one desired-state operation.
   */
  private async applyResumeWithQuality(
    viewerDeviceId: string,
    mediaSessionId: string,
    sender: RTCRtpSender,
    mapping: ViewerMapping,
  ): Promise<ReconcileResult> {
    const bId = ViewerMediaBinding.bindingIdFromMapping(mapping);

    // Ensure senders are registered with the controller
    if (!this.senderController.hasBinding(bId)) {
      this.senderController.registerSenders(bId, {
        videoSender: mapping.videoSender,
        audioSender: mapping.audioSender,
          pc: mapping.pc,
      });
    }

    // Compute effective quality from stored request
    const qualityCoordinator = this.runtime.getQualityCoordinator();
    let effective: import("@screenlink/shared").EffectiveQualityResult["effective"] | undefined;
    let sourceDimensions = { width: 1920, height: 1080 };
    let revision: number | undefined;

    if (qualityCoordinator) {
      const request = qualityCoordinator.getViewerRequest(
        mapping.groupId, mapping.logicalStreamId, viewerDeviceId,
      );
      if (request) {
        const syncState = this.runtime.getSyncService().getSyncState(mapping.groupId);
        const q = syncState?.state?.defaultQuality?.value;
        const groupSettings = q ?? createDefaultGroupQualitySettings();
        const ssm = this.runtime.getStreamSessionManager();
        const actualDims = ssm.getActualCaptureDimensions?.() ?? {};
        sourceDimensions = {
          width: actualDims.width || groupSettings.video.sendWidth || 1920,
          height: actualDims.height || groupSettings.video.sendHeight || 1080,
        };
        const runtimeLimits = this.runtime.getHostQualityLimits();
        const hostLimits: HostQualityLimits = {
          maxVideoBitrateKbps: runtimeLimits.maxVideoBitrateKbps,
          maxWidth: runtimeLimits.maxWidth,
          maxHeight: runtimeLimits.maxHeight,
          maxFps: runtimeLimits.maxFps,
          allowViewerQualityRequests: runtimeLimits.allowViewerQualityRequests,
        };
        const resolved = this.senderController.computeEffectiveQuality(
          groupSettings, hostLimits, request, sourceDimensions,
        );
        effective = resolved.effective;
        revision = request.revision;
      }
    }

    // Delegate to controller for the single setParameters write.
    // The controller handles active=true, media mode, and quality in one operation.
    const result = await this.senderController.applyResume(bId, {
      paused: false,
      videoEnabled: true,
      effective,
      revision,
    }, sourceDimensions);

    if (result.status !== "applied") {
      return result.status === "apply-failed"
        ? { status: "apply-failed" as const, error: result.error ?? "unknown error" }
        : { status: result.status === "binding-not-found" ? ("mapping-missing" as const) : ("sender-not-ready" as const) };
    }

    // Clear paused state
    const key = ViewerMediaBinding.compositeKey(viewerDeviceId, mediaSessionId);
    // viewerPausedSenderStates removed in Phase 6C — controller is authoritative

    // Send quality feedback
    const conn = this.runtime.getConnectionManager().getConnection(mapping.groupId);
    const peerUuid = conn?.peerForDevice(viewerDeviceId);
    if (conn && peerUuid && result.configured) {
      void conn.sendToPeer(peerUuid, {
        type: "quality.effective",
        streamSessionId: mapping.logicalStreamId,
        videoBitrateKbps: result.configured.maxBitrate ? Math.round(result.configured.maxBitrate / 1000) : undefined,
        maxWidth: undefined,
        maxHeight: undefined,
        maxFps: result.configured!.maxFramerate ?? undefined,
        degradationPreference: result.configured!.degradationPreference ?? undefined,
        clampReasons: [],
      }).catch(() => {});

      void conn.sendToPeer(peerUuid, {
        type: "quality.configured",
        streamSessionId: mapping.logicalStreamId,
        videoBitrateKbps: result.configured!.maxBitrate ? Math.round(result.configured!.maxBitrate / 1000) : undefined,
        maxFramerate: result.configured!.maxFramerate ?? undefined,
        scaleResolutionDownBy: result.configured!.scaleResolutionDownBy ?? undefined,
        degradationPreference: result.configured!.degradationPreference ?? undefined,
      }).catch(() => {});
    }

    return { status: "applied", configured: result.configured! };
  }

  // ─── Viewer media request (audio/video enable) ──────────────────

  /**
   * Handle a viewer.media.request from a viewer. Toggles audio and/or video
   * sender encoding independently to save bandwidth (host stops encoding
   * unwanted senders).
   *
   * Both audio and video senders are handled independently, each wrapped
   * in try/catch. If a sender is not found (null), the operation is silently
   * skipped — the sender may arrive later and the default binding path will
   * start with active=true (which is fine).
   *
   * When re-enabling video, calls applyResumeWithQuality() to reactivate
   * encoding AND restore quality settings in one setParameters call.
   */
  async handleViewerMediaRequest(
    viewerDeviceId: string,
    mediaSessionId: string,
    audioEnabled: boolean,
    videoEnabled: boolean,
  ): Promise<void> {
    if (this.destroyed) return;

    const key = ViewerMediaBinding.compositeKey(viewerDeviceId, mediaSessionId);
    const mapping = this.viewerMap.get(key);
    if (!mapping) return;

    // Store the mode preference so pause/resume respects it
    this.viewerMediaModes.set(key, { audioEnabled, videoEnabled });

    const bId = ViewerMediaBinding.bindingIdFromMapping(mapping);

    // Ensure senders are registered with the controller
    if (!this.senderController.hasBinding(bId)) {
      this.senderController.registerSenders(bId, {
        videoSender: mapping.videoSender,
        audioSender: mapping.audioSender,
          pc: mapping.pc,
      });
    }

    // Compute effective quality if re-enabling video with a stored viewer request
    let effective: import("@screenlink/shared").EffectiveQualityResult["effective"] | undefined;
    let sourceDimensions = { width: 1920, height: 1080 };

    if (videoEnabled) {
      const qualityCoordinator = this.runtime.getQualityCoordinator();
      if (qualityCoordinator) {
        const request = qualityCoordinator.getViewerRequest(
          mapping.groupId, mapping.logicalStreamId, viewerDeviceId,
        );
        if (request) {
          const syncState = this.runtime.getSyncService().getSyncState(mapping.groupId);
          const q = syncState?.state?.defaultQuality?.value;
          const groupSettings = q ?? createDefaultGroupQualitySettings();
          const ssm = this.runtime.getStreamSessionManager();
          const actualDims = ssm.getActualCaptureDimensions?.() ?? {};
          sourceDimensions = {
            width: actualDims.width || groupSettings.video.sendWidth || 1920,
            height: actualDims.height || groupSettings.video.sendHeight || 1080,
          };
          const runtimeLimits = this.runtime.getHostQualityLimits();
          const hostLimits: HostQualityLimits = {
            maxVideoBitrateKbps: runtimeLimits.maxVideoBitrateKbps,
            maxWidth: runtimeLimits.maxWidth,
            maxHeight: runtimeLimits.maxHeight,
            maxFps: runtimeLimits.maxFps,
            allowViewerQualityRequests: runtimeLimits.allowViewerQualityRequests,
          };
          const resolved = this.senderController.computeEffectiveQuality(
            groupSettings, hostLimits, request, sourceDimensions,
          );
          effective = resolved.effective;
        }
      }
    }

    // Delegate entirely to the controller for audio/video toggle + quality
    // Phase 6B: Only ViewerSenderController calls setParameters for viewer paths.
    const result = await this.senderController.applyMediaMode(
      bId, audioEnabled, videoEnabled, sourceDimensions, effective,
    );

    if (result.status !== "applied" && !result.status.startsWith("stale")) {
      console.warn(
        '[ViewerMediaBinding] applyMediaMode returned non-applied',
        { viewerDeviceId, mediaSessionId, audioEnabled, videoEnabled, result },
      );
    }
  }

  // ─── Legacy single-key methods (backward compat) ──────────────────
  //
  // These methods look up by viewerDeviceId only, searching across all
  // composite entries. They work correctly for the pre-compare (single
  // session) case. In compare mode with multiple entries for the same
  // device, they return the first match. Callers should prefer the new
  // composite-key methods for exact targeting.

  /**
   * Get the media peer UUID for a viewer device ID.
   * Searches across all composite entries.
   * Returns null if not found.
   */
  getViewerMediaPeer(viewerDeviceId: string): string | null {
    for (const [, mapping] of this.viewerMap) {
      if (mapping.viewerDeviceId === viewerDeviceId) {
        return mapping.mediaPeerUuid;
      }
    }
    return null;
  }

  /**
   * Get the video RTCRtpSender for a specific viewer.
   * Searches across all composite entries. Returns the first match.
   * Returns null if the viewer is not mapped or sender is unavailable.
   */
  getViewerVideoSender(viewerDeviceId: string): RTCRtpSender | null {
    for (const [, mapping] of this.viewerMap) {
      if (mapping.viewerDeviceId === viewerDeviceId) {
        return mapping.videoSender ?? null;
      }
    }
    return null;
  }

  /**
   * Get the audio RTCRtpSender for a specific viewer.
   * Searches across all composite entries. Returns the first match.
   * Returns null if the viewer is not mapped or sender is unavailable.
   */
  getViewerAudioSender(viewerDeviceId: string): RTCRtpSender | null {
    for (const [, mapping] of this.viewerMap) {
      if (mapping.viewerDeviceId === viewerDeviceId) {
        return mapping.audioSender ?? null;
      }
    }
    return null;
  }

  /**
   * Get the RTCPeerConnection for a specific viewer.
   * Searches across all composite entries. Returns the first match.
   * Returns null if the viewer is not mapped or PC is unavailable.
   */
  getViewerPeerConnection(viewerDeviceId: string): RTCPeerConnection | null {
    for (const [, mapping] of this.viewerMap) {
      if (mapping.viewerDeviceId === viewerDeviceId) {
        return mapping.pc ?? null;
      }
    }
    return null;
  }

  // ─── Explicit composite-key methods ──────────────────────────────

  /**
   * Get all viewer mappings for a specific media session.
   * Useful for per-session cleanup and diagnostics.
   */
  getViewersForMediaSession(mediaSessionId: string): ViewerMapping[] {
    const result: ViewerMapping[] = [];
    for (const [, mapping] of this.viewerMap) {
      if (mapping.mediaSessionId === mediaSessionId) {
        result.push(mapping);
      }
    }
    return result;
  }

  /**
   * Get viewer mapping by exact composite key (viewerDeviceId + mediaSessionId).
   * Returns the exact mapping for this device + session combination,
   * or null if not found. All callers must provide both IDs — no legacy
   * first-match fallback (Phase 2).
   */
  getViewerMapping(viewerDeviceId: string, mediaSessionId: string): ViewerMapping | null {
    return this.viewerMap.get(ViewerMediaBinding.compositeKey(viewerDeviceId, mediaSessionId)) ?? null;
  }

  /**
   * Remove a viewer mapping by exact composite key.
   * Accepts an optional `viewerSessionId`. When provided, the mapping is
   * only removed if the stored session ID matches.
   *
   * Returns true if a mapping was removed.
   */
  removeViewerMapping(viewerDeviceId: string, mediaSessionId: string, viewerSessionId?: string): boolean {
    const key = ViewerMediaBinding.compositeKey(viewerDeviceId, mediaSessionId);
    const mapping = this.viewerMap.get(key);
    if (!mapping) return false;

    // Stale session guard: if a viewerSessionId is provided and it does not
    // match the stored mapping, reject the removal.
    if (viewerSessionId && mapping.viewerSessionId !== viewerSessionId) {
      return false;
    }

    // Unregister senders from the controller
    this.senderController.unregisterSenders(ViewerMediaBinding.bindingIdFromMapping(mapping));

    this.viewerMap.delete(key);
    this.viewerMediaModes.delete(key);
    // viewerPausedSenderStates removed in Phase 6C — controller is authoritative
    return true;
  }

  /**
   * Remove all viewer mappings for the given media session IDs.
   * Returns the number of mappings removed.
   */
  removeMappingsForMediaSessions(mediaSessionIds: string[]): number {
    const sessionSet = new Set(mediaSessionIds);
    let removed = 0;
    for (const [key, mapping] of this.viewerMap) {
      if (sessionSet.has(mapping.mediaSessionId)) {
        this.senderController.unregisterSenders(ViewerMediaBinding.bindingIdFromMapping(mapping));
        this.viewerMap.delete(key);
        this.viewerMediaModes.delete(key);
        // viewerPausedSenderStates removed in Phase 6C — controller is authoritative
        removed++;
      }
    }
    return removed;
  }

  /**
   * Get unique viewer device IDs for a logical stream.
   * Deduplicates by viewerDeviceId so a device watching both A and B variants
   * counts as one human viewer.
   */
  getUniqueViewerDevicesForLogicalStream(logicalStreamId: string): string[] {
    const devices = new Set<string>();
    for (const [, mapping] of this.viewerMap) {
      if (mapping.logicalStreamId === logicalStreamId) {
        devices.add(mapping.viewerDeviceId);
      }
    }
    return Array.from(devices);
  }

  // ─── Legacy removal removed in Phase 2.
  // All callers now use removeViewerMapping() (exact composite key),
  // removeViewerByPeerUuid(), or removeMappingsForMediaSessions().

  /**
   * Remove a viewer by media peer UUID. Used by the host's SDK
   * `peerDisconnected` handler so that an abrupt disconnect (where
   * no `stream.leave` ever arrives) still cleans up ScreenLink-owned
   * state. The PC close itself is left to the SDK.
   */
  removeViewerByPeerUuid(mediaPeerUuid: string, immediate?: boolean): boolean {
    for (const [key, mapping] of this.viewerMap) {
      if (mapping.mediaPeerUuid === mediaPeerUuid) {
        const presence = this.getViewerPresence(mapping.viewerDeviceId, mapping.mediaSessionId);
        if (!presence) {
          this.senderController.unregisterSenders(ViewerMediaBinding.bindingIdFromMapping(mapping));
          this.viewerMap.delete(key);
          this.viewerMediaModes.delete(key);
          // viewerPausedSenderStates removed in Phase 6C — controller is authoritative
          return true;
        }

        const departed = this.markViewerDeparted(mapping.viewerDeviceId, mapping.mediaSessionId, {
          viewerSessionId: mapping.viewerSessionId,
          immediate,
        });
        if (immediate) {
          this.senderController.unregisterSenders(ViewerMediaBinding.bindingIdFromMapping(mapping));
          this.viewerMap.delete(key);
          this.viewerMediaModes.delete(key);
          // viewerPausedSenderStates removed in Phase 6C — controller is authoritative
        }
        return departed;
      }
    }
    return false;
  }

  /**
   * Get a binding token by its token string.
   */
  getBindingToken(token: string): BindingToken | undefined {
    return this.tokens.get(token);
  }

  /**
   * Stage 5: Get all mapped viewers.
   * Used by StreamSessionManager.stopStream() to clean up on stream stop.
   */
  getAllViewers(): ViewerMapping[] {
    return Array.from(this.viewerMap.values());
  }

  /**
   * Get composite human-readable viewers (deduplicated by viewerDeviceId).
   */
  getHumanViewerCount(): number {
    return this.getHumanViewers().length;
  }

  /**
   * Get all unique viewer device IDs watching any stream on this host.
   */
  getHumanViewers(): Array<{ viewerDeviceId: string }> {
    const seen = new Set<string>();
    const result: Array<{ viewerDeviceId: string }> = [];
    for (const [, mapping] of this.viewerMap) {
      if (!seen.has(mapping.viewerDeviceId)) {
        seen.add(mapping.viewerDeviceId);
        result.push({
          viewerDeviceId: mapping.viewerDeviceId,
        });
      }
    }
    return result;
  }

  /**
   * Destroy the binding manager. Terminates cleanup timer and clears all state.
   */
  destroy(): void {
    this.destroyed = true;
    this.destroyPresences();
    this.tokens.clear();
    this.viewerMap.clear();
    this.viewerMediaModes.clear();
    this.processedRequests.clear();
    if (this._fallbackSenderController) {
      this._fallbackSenderController.destroy();
      this._fallbackSenderController = null;
    }
    if (this.cleanupTimer) {
      clearInterval(this.cleanupTimer);
      this.cleanupTimer = null;
    }
  }

  // ── Private ──────────────────────────────────────────────────

  private startCleanup(): void {
    if (this.cleanupTimer) return;
    this.cleanupTimer = setInterval(() => {
      this.cleanupExpiredTokens();
    }, this.CLEANUP_INTERVAL_MS);
  }

  private cleanupExpiredTokens(): void {
    const now = Date.now();
    for (const [token, bt] of this.tokens) {
      if (now > bt.expiresAt) {
        this.tokens.delete(token);
      }
    }
    // Also clean up stale processed request entries (older than TTL)
    for (const [reqId, token] of this.processedRequests) {
      const bt = this.tokens.get(token);
      if (!bt) {
        this.processedRequests.delete(reqId);
      }
    }
  }

  /**
   * Build a minimal StreamAnnouncement from StreamSessionManager's public state.
   * Used for self-healing when the registry entry is missing.
   */
  private buildSsmAnnouncement(
    ssm: import("./stream-session-manager.js").StreamSessionManager,
    hostDeviceId: string,
  ): import("@screenlink/shared").StreamAnnouncement {
    return {
      logicalStreamId: ssm.currentLogicalStreamId ?? "",
      mediaSessionId: ssm.currentMediaSessionId ?? "",
      groupId: ssm.currentGroupId ?? "",
      hostDeviceId,
      hostDisplayName: "",
      sourceKind: "screen",
      sourceName: "",
      startedAt: 0,
      appliedSettingsRevision: 0,
      heartbeatSequence: 0,
      streamRevision: 0,
      mediaJoinMetadata: "",
      replacesSessionId: null,
    };
  }

  private base64URLEncode(bytes: Uint8Array): string {
    // Convert to binary string, then btoa, then make URL-safe
    let binary = "";
    for (let i = 0; i < bytes.length; i++) {
      binary += String.fromCharCode(bytes[i]);
    }
    return btoa(binary)
      .replace(/\+/g, "-")
      .replace(/\//g, "_")
      .replace(/=+$/, "");
  }

  // ─── Viewer presence lifecycle (join/leave audio cues) ─────────────
  //
  // Tracks viewer presence by composite key with explicit states:
  //   accepted → media-bound → ready → departed
  //
  // Join cue fires once: not-ready → ready
  // Leave cue fires once: ready → departed  (only if previously became ready)
  //
  // A grace period (VIEWER_DISCONNECT_GRACE_MS) allows recovery from
  // transient disconnections without firing a leave cue.

  /** Grace period (ms) for transient disconnects before firing leave cue */
  private static readonly VIEWER_DISCONNECT_GRACE_MS = 30_000;

  /** Presence map keyed by composite key (viewerDeviceId::mediaSessionId) */
  private presenceMap = new Map<string, ViewerPresence>();

  /** Callback fired when a join or leave cue should be played */
  onViewerCue: ViewerCueCallback | null = null;

  /**
   * Handle a `stream.viewer.ready` message from a viewer.
   * Transitions the viewer's presence from accepted/media-bound to ready.
   *
   * Rules:
   * - Join cue fired ONLY on the first ready transition (not-ready → ready).
   * - Duplicate ready messages (same composite key, already ready) are ignored.
   * - The viewer must have a valid binding mapping.
   *
   * Returns true if this was the first ready transition (join cue triggered).
   */
  handleViewerReady(
    viewerDeviceId: string,
    viewerSessionId: string,
    mediaSessionId: string,
    logicalStreamId: string,
    presentation: "native-video" | "webgl" | "nvidia" | "fallback",
  ): boolean {
    const key = ViewerMediaBinding.compositeKey(viewerDeviceId, mediaSessionId);
    let presence = this.presenceMap.get(key);

    if (!presence) {
      // Create new presence if one doesn't exist
      presence = {
        viewerDeviceId,
        viewerSessionId,
        mediaSessionId,
        logicalStreamId,
        state: "accepted",
        joinCuePlayed: false,
        leaveCuePlayed: false,
      };
      this.presenceMap.set(key, presence);
    }

    // Stale session guard: reject if viewerSessionId doesn't match
    if (presence.viewerSessionId !== viewerSessionId) return false;

    // Already ready — duplicate message, ignore
    if (presence.state === "ready") return false;
    if (presence.state === "departed") return false;

    // Cancel any pending grace timer (viewer reconnected before timeout)
    if (presence.graceTimer) {
      clearTimeout(presence.graceTimer);
      presence.graceTimer = undefined;
    }

    // Transition to ready
    presence.state = "ready";
    presence.readyAt = Date.now();

    // Fire join cue if this is the first ready transition
    if (!presence.joinCuePlayed) {
      presence.joinCuePlayed = true;
      this.onViewerCue?.("user-join", presence);
      return true;
    }

    return false;
  }

  /**
   * Mark a viewer as departed. May be called from stream.leave,
   * VDO peerDisconnected, or host-side cleanup.
   *
   * If the viewer was in "ready" state:
   *   - If graceful (explicit leave): fires leave cue immediately.
   *   - If abrupt (disconnect): starts a grace timer. If the viewer
   *     reconnects before the timer fires, the departure is cancelled.
   *     If the timer fires, the leave cue plays.
   *
   * During destroy/shutdown, pass `immediate=true` to suppress the
   * leave cue entirely (no sounds during cleanup).
   */
  markViewerDeparted(
    viewerDeviceId: string,
    mediaSessionId: string,
    options?: { immediate?: boolean; viewerSessionId?: string; explicit?: boolean },
  ): boolean {
    const key = ViewerMediaBinding.compositeKey(viewerDeviceId, mediaSessionId);
    const presence = this.presenceMap.get(key);
    if (!presence) return false;

    // Stale session guard
    if (options?.viewerSessionId && presence.viewerSessionId !== options.viewerSessionId) return false;

    // Already departed — no-op
    if (presence.state === "departed") return false;

    // Never became ready — no leave cue, just clean up
    if (presence.state !== "ready") {
      presence.state = "departed";
      presence.departedAt = Date.now();
      presence.leaveCuePlayed = true; // Don't play leave for never-ready
      this.presenceMap.delete(key);
      const mapping = this.viewerMap.get(key);
      if (mapping) {
        this.viewerMap.delete(key);
      }
      return true;
    }

    // Cancel any existing grace timer
    if (presence.graceTimer) {
      clearTimeout(presence.graceTimer);
      presence.graceTimer = undefined;
    }

    if (options?.explicit) {
      presence.state = "departed";
      presence.departedAt = Date.now();
      if (!presence.leaveCuePlayed && presence.joinCuePlayed) {
        presence.leaveCuePlayed = true;
        this.onViewerCue?.("user-leave", presence);
      }
      this.presenceMap.delete(key);
      const mapping = this.viewerMap.get(key);
      if (mapping) {
        this.viewerMap.delete(key);
      }
      return true;
    }

    if (options?.immediate) {
      // Shutdown/cleanup: no leave cue
      presence.state = "departed";
      presence.departedAt = Date.now();
      presence.leaveCuePlayed = true;
      this.presenceMap.delete(key);
      const mapping = this.viewerMap.get(key);
      if (mapping) {
        this.viewerMap.delete(key);
      }
      return true;
    }

    // Grace period for transient disconnects
    // Start grace timer
    presence.state = "departed"; // Optimistically mark departed
    presence.departedAt = Date.now();

    presence.graceTimer = setTimeout(() => {
      const current = this.presenceMap.get(key);
      if (!current || current.graceTimer === undefined) return;

      // If viewer never came back, play leave cue
      if (!current.leaveCuePlayed && current.joinCuePlayed) {
        current.leaveCuePlayed = true;
        this.onViewerCue?.("user-leave", current);
      }
      const mapping = this.viewerMap.get(key);
      if (mapping) {
        this.viewerMap.delete(key);
      }
      this.presenceMap.delete(key);
    }, ViewerMediaBinding.VIEWER_DISCONNECT_GRACE_MS);

    return true;
  }

  /**
   * Remove viewer mapping with presence lifecycle integration.
   * Overrides the legacy removeViewer for presence tracking.
   * Call this instead of removeViewer when presence cues are active.
   */
  removeViewerWithPresence(
    viewerDeviceId: string,
    mediaSessionId: string,
    viewerSessionId?: string,
    immediate?: boolean,
  ): boolean {
    return this.markViewerDeparted(viewerDeviceId, mediaSessionId, {
      viewerSessionId,
      immediate,
      explicit: !immediate,
    });
  }

  /**
   * Cancel a pending departure (viewer reconnected within grace period).
   * Returns the presence if it was recovered, null if no recovery needed.
   */
  recoverViewerPresence(
    viewerDeviceId: string,
    mediaSessionId: string,
    viewerSessionId: string,
    nextState: "media-bound" | "ready" = "media-bound",
  ): ViewerPresence | null {
    const key = ViewerMediaBinding.compositeKey(viewerDeviceId, mediaSessionId);
    const presence = this.presenceMap.get(key);
    if (!presence) return null;

    // Stale session guard
    if (presence.viewerSessionId !== viewerSessionId) return null;

    // If the viewer is already departed and leave cue wasn't played yet,
    // cancel the grace timer and mark as recovered
    if (presence.state === "departed" && !presence.leaveCuePlayed) {
      if (presence.graceTimer) {
        clearTimeout(presence.graceTimer);
        presence.graceTimer = undefined;
      }
      presence.state = nextState;
      presence.departedAt = undefined;
      return presence;
    }

    return null;
  }

  /**
   * Get all active presence entries (not departed).
   */
  getActivePresences(): ViewerPresence[] {
    return Array.from(this.presenceMap.values())
      .filter((p) => p.state !== "departed");
  }

  /**
   * Get the presence for a specific viewer, or null if not found.
   */
  getViewerPresence(viewerDeviceId: string, mediaSessionId: string): ViewerPresence | null {
    const key = ViewerMediaBinding.compositeKey(viewerDeviceId, mediaSessionId);
    return this.presenceMap.get(key) ?? null;
  }

  /**
   * Clean up all presence entries (during destroy, no leave cues).
   */
  private destroyPresences(): void {
    for (const [key, presence] of this.presenceMap) {
      if (presence.graceTimer) {
        clearTimeout(presence.graceTimer);
      }
    }
    this.presenceMap.clear();
  }

  private upsertPresence(input: {
    viewerDeviceId: string;
    viewerSessionId: string;
    mediaSessionId: string;
    logicalStreamId: string;
    state: "accepted" | "media-bound";
  }): ViewerPresence {
    const key = ViewerMediaBinding.compositeKey(input.viewerDeviceId, input.mediaSessionId);
    const existing = this.presenceMap.get(key);

    if (existing && existing.viewerSessionId === input.viewerSessionId) {
      if (existing.graceTimer) {
        clearTimeout(existing.graceTimer);
        existing.graceTimer = undefined;
      }
      if (existing.state !== "ready") {
        existing.state = input.state;
      }
      existing.departedAt = undefined;
      return existing;
    }

    if (existing?.graceTimer) {
      clearTimeout(existing.graceTimer);
    }

    const presence: ViewerPresence = {
      viewerDeviceId: input.viewerDeviceId,
      viewerSessionId: input.viewerSessionId,
      mediaSessionId: input.mediaSessionId,
      logicalStreamId: input.logicalStreamId,
      state: input.state,
      joinCuePlayed: false,
      leaveCuePlayed: false,
    };
    this.presenceMap.set(key, presence);
    return presence;
  }
}
