import type { GroupControlEnvelope } from "@screenlink/shared";
import type { Phase3Runtime } from "./phase3-runtime.js";
import type { StreamAnnouncement } from "./active-stream-registry.js";

/**
 * Binding token created by the host for a viewer's stream.join.request.
 * The viewer must present this token via media.bind to be granted a peer connection.
 */
export interface BindingToken {
  token: string;
  groupId: string;
  logicalStreamId: string;
  mediaSessionId: string;
  viewerDeviceId: string;
  /**
   * Per-attempt session ID generated by the viewer for every Watch attempt.
   * Carried through the join → bind → leave flow so the host can
   * disambiguate attempts that share the same viewerDeviceId.
   */
  viewerSessionId: string;
  createdAt: number;
  expiresAt: number;
  consumed: boolean;
}

/**
 * Extended viewer mapping with complete binding context.
 * Stores enough information to support exact viewer operations:
 * sender quality apply, per-viewer stats, and deterministic cleanup.
 */
export interface ViewerMapping {
  viewerDeviceId: string;
  /**
   * Per-attempt session ID for this viewer. A new Watch attempt by the
   * same device gets a new ID; the host uses it to reject stale leave
   * messages that were sent by a prior attempt before the user re-joined.
   */
  viewerSessionId: string;
  mediaPeerUuid: string;
  groupId: string;
  logicalStreamId: string;
  mediaSessionId: string;
  /** The RTCPeerConnection for this viewer's media, used for sender access and stats */
  pc: RTCPeerConnection | null;
  /** The video RTCRtpSender for this viewer, used for quality application */
  videoSender: RTCRtpSender | null;
  /** The audio RTCRtpSender for this viewer, used for diagnostics and per-viewer audio control */
  audioSender: RTCRtpSender | null;
}

export interface ConsumeBindingInput {
  token: string;
  viewerDeviceId: string;
  /**
   * Per-attempt session ID. Must match the token's stored ID for the
   * binding to be accepted — prevents a delayed bind from a prior
   * attempt from being mis-applied to a newer session.
   */
  viewerSessionId: string;
  groupId: string;
  logicalStreamId: string;
  mediaSessionId: string;
  mediaPeerUuid: string;
}

/**
 * Composite-key separator for viewer mappings.
 * Used to construct keys of the form `${viewerDeviceId}::${mediaSessionId}`.
 */
const COMPOSITE_KEY_SEP = "::";

/**
 * C5: ViewerMediaBinding (Stages 4–5)
 *
 * Manages one-time binding tokens that authorize a viewer to attach
 * to a specific media session. The host:
 * 1. Receives stream.join.request → generates token
 * 2. Viewer presents token via media.bind data channel message
 * 3. Host validates and marks consumed
 *
 * Stage 5 enhancements:
 * - consumeBinding(): full validation of token + viewer/group/logicalStream/mediaSession/peerConnection/senders
 * - Duplicate request idempotency via requestId tracking
 * - getAllViewers() for cleanup on stream stop
 * - Viewer disconnect preserves other viewers
 *
 * Compare-mode (Task 2):
 * - viewerMap uses composite key `viewerDeviceId::mediaSessionId` so one device
 *   may hold A and B bindings simultaneously.
 * - Explicit composite-key methods for exact leave/remove/disconnect.
 * - Legacy removeViewer path is safe for non-compare messages.
 * - Unique human counting deduplicates by viewerDeviceId.
 */
export class ViewerMediaBinding {
  private tokens = new Map<string, BindingToken>();
  /**
   * Composite-keyed viewer mapping.
   * Key format: `${viewerDeviceId}::${mediaSessionId}`
   * This allows one device to hold bindings for multiple media sessions
   * simultaneously (compare mode A + B).
   */
  private viewerMap = new Map<string, ViewerMapping>();
  /** Track processed requestIds for idempotency */
  private processedRequests = new Map<string, string>(); // requestEnvelopeId → token
  private cleanupTimer: ReturnType<typeof setInterval> | null = null;
  private destroyed = false;
  private readonly TOKEN_TTL_MS = 60_000; // 60 seconds
  private readonly CLEANUP_INTERVAL_MS = 30_000; // every 30s

  constructor(private runtime: Phase3Runtime) {
    this.startCleanup();
  }

  /** Build a composite key from viewer device ID and media session ID. */
  private static compositeKey(viewerDeviceId: string, mediaSessionId: string): string {
    return `${viewerDeviceId}${COMPOSITE_KEY_SEP}${mediaSessionId}`;
  }

  /**
   * Called by host when stream.join.request arrives via group control.
   * Validates the sender has a valid group with an active stream,
   * generates a one-time token, stores it, and sends a response back
   * to the requesting viewer via group control.
   *
   * Uses the real host device ID from the runtime (not hardcoded "local").
   * Stage 5: Duplicate requestId returns the same token (idempotent).
   *
   * Returns null if no active stream is found for the group (but sends
   * an explicit rejection so the viewer does not time out). Returns
   * null on other failures as well.
   */
  handleJoinRequest(envelope: GroupControlEnvelope): { mediaSessionId: string; token: string; viewerSessionId: string } | null {
    if (this.destroyed) return null;

    const groupId = envelope.groupId;
    const viewerDeviceId = envelope.senderDeviceId;
    const payload = envelope.payload as Record<string, unknown> | undefined;
    const logicalStreamId = payload?.logicalStreamId as string | undefined;
    const requestId = payload?.requestId as string | undefined;
    // Optional per-attempt session ID. If the viewer is on an older build
    // that doesn't generate one, we synthesize a stable identifier from
    // the envelope's messageId so the token still carries something the
    // host can use to reject stale leaves for THIS specific attempt.
    const viewerSessionId =
      (payload?.viewerSessionId as string | undefined) ??
      (envelope.messageId ?? `legacy-${viewerDeviceId ?? "unknown"}-${requestId ?? Date.now().toString()}`);
    // Compare correlation fields (optional — viewer omits for legacy A-only join)
    const compareVariantId = payload?.compareVariantId as string | undefined;
    const requestedMediaSessionId = payload?.mediaSessionId as string | undefined;

    if (!viewerDeviceId || !logicalStreamId) {
      // Send rejection for invalid request so the viewer doesn't time out
      this.sendJoinRejection(
        envelope,
        requestId,
        !viewerDeviceId ? "Invalid viewer identity" : "Missing stream identifier",
        compareVariantId,
        requestedMediaSessionId,
      );
      return null;
    }

    // Stage 5: Check for duplicate request (same envelope messageId)
    if (envelope.messageId && this.processedRequests.has(envelope.messageId)) {
      const existingToken = this.processedRequests.get(envelope.messageId)!;
      const bt = this.tokens.get(existingToken);
      if (bt && !bt.consumed) {
        return { mediaSessionId: bt.mediaSessionId, token: existingToken, viewerSessionId: bt.viewerSessionId };
      }
    }

    // Use the real host device ID from the runtime, not hardcoded "local"
    const hostDeviceId = this.runtime.deviceId ?? "local";

    // Verify this group has an active stream matching the request
    const registry = this.runtime.getActiveStreamRegistry();
    const stream = registry.getStream({
      groupId,
      hostDeviceId,
      logicalStreamId,
    });
    if (!stream) {
      // Send explicit rejection instead of forcing a timeout
      this.sendJoinRejection(
        envelope,
        requestId,
        "There is no active share for this stream",
        compareVariantId,
        requestedMediaSessionId,
      );
      return null;
    }

    // ── Compare-mode target media session resolution ──────────────
    // If the viewer included compare correlation fields, resolve the
    // exact media session they intend to join (A variant or B variant).
    // Legacy requests (no compare fields) use the primary stream session.
    const resolved = this.resolveTargetMediaSession(
      stream,
      compareVariantId,
      requestedMediaSessionId,
    );
    if (!resolved) {
      const reason = requestedMediaSessionId && !compareVariantId
        ? `Requested media session "${requestedMediaSessionId}" not found`
        : compareVariantId
          ? `Requested compare variant "${compareVariantId}" is not available`
          : "Could not resolve a valid media session for this request";
      this.sendJoinRejection(envelope, requestId, reason, compareVariantId, requestedMediaSessionId);
      return null;
    }
    const effectiveMediaSessionId = resolved.mediaSessionId;

    // Generate 32 random bytes → Base64URL token
    const rawBytes = new Uint8Array(32);
    crypto.getRandomValues(rawBytes);
    const token = this.base64URLEncode(rawBytes);

    const now = Date.now();
    const bindingToken: BindingToken = {
      token,
      groupId,
      logicalStreamId,
      mediaSessionId: effectiveMediaSessionId,
      viewerDeviceId,
      viewerSessionId,
      createdAt: now,
      expiresAt: now + this.TOKEN_TTL_MS,
      consumed: false,
    };

    this.tokens.set(token, bindingToken);

    // Track for idempotency
    if (envelope.messageId) {
      this.processedRequests.set(envelope.messageId, token);
    }

    // Send join response back to the requesting viewer
    this.sendJoinResponse(envelope, token, effectiveMediaSessionId, requestId, viewerSessionId, resolved.variantId).catch(() => {});

    return {
      mediaSessionId: effectiveMediaSessionId,
      token,
      viewerSessionId,
    };
  }

  /**
   * Send a stream.join.response with accepted=false and a user-facing reason.
   * Prevents the viewer from timing out when the host cannot satisfy the request
   * (e.g. no active stream, invalid parameters).
   */
  private async sendJoinRejection(
    requestEnvelope: GroupControlEnvelope,
    requestId: string | undefined,
    reason: string,
    compareVariantId?: string,
    requestedMediaSessionId?: string,
  ): Promise<void> {
    const conn = this.runtime.getConnectionManager().getConnection(requestEnvelope.groupId);
    if (!conn) return;
    const peerUuid = conn.peerForDevice(requestEnvelope.senderDeviceId);
    if (!peerUuid) return;

    const payload = requestEnvelope.payload as Record<string, unknown> | undefined;
    const viewerSessionId = payload?.viewerSessionId as string | undefined;
    const logicalStreamId = (payload?.logicalStreamId as string) ?? "";

    try {
      await conn.sendToPeer(peerUuid, {
        type: "stream.join.response",
        logicalStreamId,
        accepted: false,
        viewerDeviceId: requestEnvelope.senderDeviceId,
        reason,
        requestId: requestId ?? "",
        ...(viewerSessionId ? { viewerSessionId } : {}),
        ...(compareVariantId ? { compareVariantId } : {}),
        ...(requestedMediaSessionId ? { mediaSessionId: requestedMediaSessionId } : {}),
      });
    } catch {
      // Best-effort rejection — if the connection is gone the viewer will time out
    }
  }

  /**
   * Send a stream.join.response back to the requesting viewer via group control.
   * Includes VDO media credentials (streamId, password, bindingToken) so the
   * viewer can connect directly via ViewerClient without local host config.
   *
   * Uses resolveLocalPublication() to find the correct publication for the
   * given media session, which works for both normal and compare mode variants.
   */
  private async sendJoinResponse(
    requestEnvelope: GroupControlEnvelope,
    token: string,
    mediaSessionId: string,
    requestId?: string,
    viewerSessionId?: string,
    compareVariantId?: string,
  ): Promise<void> {
    const conn = this.runtime.getConnectionManager().getConnection(requestEnvelope.groupId);
    if (!conn) return;
    const peerUuid = conn.peerForDevice(requestEnvelope.senderDeviceId);
    if (!peerUuid) return;

    // Resolve the publication for this media session (works for both normal
    // and compare mode). The runtime checks compare variants first, then
    // falls back to the normal StreamSessionManager.
    const publication = this.runtime.resolveLocalPublication(mediaSessionId);
    const streamId = publication?.vdoConfig.streamId;
    const password = publication?.vdoConfig.password;

    await conn.sendToPeer(peerUuid, {
      type: "stream.join.response",
      logicalStreamId: requestEnvelope.payload?.logicalStreamId as string,
      accepted: true,
      viewerDeviceId: requestEnvelope.senderDeviceId,
      mediaSessionId,
      mediaJoinMetadata: token,
      streamId,
      password,
      bindingToken: token,
      requestId: requestId ?? "",
      ...(viewerSessionId ? { viewerSessionId } : {}),
      ...(compareVariantId ? { compareVariantId } : {}),
    });
  }

  /**
   * Called by host when media.bind arrives via the VDO data channel.
   * Uses the real media peer UUID from the VDO SDK callback.
   *
   * Delegates to consumeBinding() with the token's stored context
   * for consistent validation across both bind paths.
   */
  async handleMediaBind(peerUuid: string, token: string, viewerSessionId?: string): Promise<boolean> {
    if (this.destroyed) return false;

    const bindingToken = this.tokens.get(token);
    if (!bindingToken) return false;
    if (bindingToken.consumed) return false;
    if (Date.now() > bindingToken.expiresAt) {
      this.tokens.delete(token);
      return false;
    }

    // Use the full consumeBinding path for consistent validation
    return this.consumeBinding({
      token,
      viewerDeviceId: bindingToken.viewerDeviceId,
      viewerSessionId: viewerSessionId ?? bindingToken.viewerSessionId,
      groupId: bindingToken.groupId,
      logicalStreamId: bindingToken.logicalStreamId,
      mediaSessionId: bindingToken.mediaSessionId,
      mediaPeerUuid: peerUuid,
    });
  }

  /**
   * Stage 5: Full binding consumption with validation.
   *
   * Validates that:
   * - The token exists and is not consumed
   * - The viewerDeviceId matches
   * - The viewerSessionId matches (when supplied)
   * - The groupId matches
   * - The logicalStreamId matches
   * - The mediaSessionId matches
   *
   * On success, deletes the token and stores the viewer mapping
   * under a composite key (viewerDeviceId::mediaSessionId).
   * Returns true if the binding was consumed successfully.
   */
  async consumeBinding(input: ConsumeBindingInput): Promise<boolean> {
    if (this.destroyed) return false;

    const bindingToken = this.tokens.get(input.token);
    if (!bindingToken) return false;
    if (bindingToken.consumed) return false;
    if (Date.now() > bindingToken.expiresAt) {
      this.tokens.delete(input.token);
      return false;
    }

    // Validate viewerDeviceId
    if (bindingToken.viewerDeviceId !== input.viewerDeviceId) return false;

    // Validate viewerSessionId when both sides have one. If the bind
    // payload omits a session ID but the token has one, we treat that
    // as a mismatch — the viewer's own join request generated the token
    // with a session ID, so any subsequent bind must carry the same one.
    if (input.viewerSessionId && bindingToken.viewerSessionId &&
        input.viewerSessionId !== bindingToken.viewerSessionId) {
      return false;
    }

    // Validate groupId
    if (bindingToken.groupId !== input.groupId) return false;

    // Validate logicalStreamId
    if (bindingToken.logicalStreamId !== input.logicalStreamId) return false;

    // Validate mediaSessionId
    if (bindingToken.mediaSessionId !== input.mediaSessionId) return false;

    // Mark consumed and delete token
    bindingToken.consumed = true;
    this.tokens.delete(input.token);

    // Try to resolve the RTCPeerConnection, video sender, and audio sender for this viewer.
    // Uses resolveLocalPublication() to find the correct publisher for the media session
    // (works for both normal and compare mode).
    let pc: RTCPeerConnection | null = null;
    let videoSender: RTCRtpSender | null = null;
    let audioSender: RTCRtpSender | null = null;
    try {
      const publication = this.runtime.resolveLocalPublication(input.mediaSessionId);
      const publisherManager = publication?.publisherManager ?? this.runtime.getStreamSessionManager().getPublisherManager();
      const hostPublisher = publisherManager?.getPublisher();
      if (hostPublisher) {
        const sdk = hostPublisher.getSDK();
        if (sdk && sdk.connections) {
          const group = sdk.connections.get(input.mediaPeerUuid);
          if (group) {
            pc = group.publisher?.pc ?? group.viewer?.pc ?? null;
            if (pc) {
              const senders = pc.getSenders();
              videoSender = senders.find(s => s.track?.kind === "video") ?? null;
              audioSender = senders.find(s => s.track?.kind === "audio") ?? null;
            }
          }
        }
      }
    } catch {
      // Sender/PC resolution is best-effort
    }

    // Store extended viewer mapping with composite key (viewerDeviceId::mediaSessionId).
    // The composite key allows one device to hold bindings for multiple media
    // sessions simultaneously (compare mode A + B).
    const key = ViewerMediaBinding.compositeKey(input.viewerDeviceId, input.mediaSessionId);
    this.viewerMap.set(key, {
      viewerDeviceId: input.viewerDeviceId,
      viewerSessionId: input.viewerSessionId ?? bindingToken.viewerSessionId,
      mediaPeerUuid: input.mediaPeerUuid,
      groupId: input.groupId,
      logicalStreamId: input.logicalStreamId,
      mediaSessionId: input.mediaSessionId,
      pc,
      videoSender,
      audioSender,
    });

    // Start per-viewer stats polling when binding is established
    if (pc) {
      const statsService = this.runtime.getMediaStatsService();
      if (statsService) {
        statsService.startViewerPoller(
          input.groupId,
          input.logicalStreamId,
          input.viewerDeviceId,
          input.mediaPeerUuid,
          pc,
          () => {
            // Stats callback — no-op for now, stats flow through store in future
          },
        );
      }
    }

    return true;
  }

  // ─── Legacy single-key methods (backward compat) ──────────────────
  //
  // These methods look up by viewerDeviceId only, searching across all
  // composite entries. They work correctly for the pre-compare (single
  // session) case. In compare mode with multiple entries for the same
  // device, they return the first match. Callers should prefer the new
  // composite-key methods for exact targeting.

  /**
   * Get the media peer UUID for a viewer device ID.
   * Searches across all composite entries.
   * Returns null if not found.
   */
  getViewerMediaPeer(viewerDeviceId: string): string | null {
    for (const [, mapping] of this.viewerMap) {
      if (mapping.viewerDeviceId === viewerDeviceId) {
        return mapping.mediaPeerUuid;
      }
    }
    return null;
  }

  /**
   * Get the video RTCRtpSender for a specific viewer.
   * Searches across all composite entries. Returns the first match.
   * Returns null if the viewer is not mapped or sender is unavailable.
   */
  getViewerVideoSender(viewerDeviceId: string): RTCRtpSender | null {
    for (const [, mapping] of this.viewerMap) {
      if (mapping.viewerDeviceId === viewerDeviceId) {
        return mapping.videoSender ?? null;
      }
    }
    return null;
  }

  /**
   * Get the audio RTCRtpSender for a specific viewer.
   * Searches across all composite entries. Returns the first match.
   * Returns null if the viewer is not mapped or sender is unavailable.
   */
  getViewerAudioSender(viewerDeviceId: string): RTCRtpSender | null {
    for (const [, mapping] of this.viewerMap) {
      if (mapping.viewerDeviceId === viewerDeviceId) {
        return mapping.audioSender ?? null;
      }
    }
    return null;
  }

  /**
   * Get the RTCPeerConnection for a specific viewer.
   * Searches across all composite entries. Returns the first match.
   * Returns null if the viewer is not mapped or PC is unavailable.
   */
  getViewerPeerConnection(viewerDeviceId: string): RTCPeerConnection | null {
    for (const [, mapping] of this.viewerMap) {
      if (mapping.viewerDeviceId === viewerDeviceId) {
        return mapping.pc ?? null;
      }
    }
    return null;
  }

  // ─── Explicit composite-key methods ──────────────────────────────

  /**
   * Get all viewer mappings for a specific media session.
   * Useful for per-session cleanup and diagnostics.
   */
  getViewersForMediaSession(mediaSessionId: string): ViewerMapping[] {
    const result: ViewerMapping[] = [];
    for (const [, mapping] of this.viewerMap) {
      if (mapping.mediaSessionId === mediaSessionId) {
        result.push(mapping);
      }
    }
    return result;
  }

  /**
   * Get viewer mapping by composite key (viewerDeviceId + mediaSessionId).
   * Returns the exact mapping for this device + session combination,
   * or null if not found.
   *
   * When called with a single argument (legacy), returns the first mapping
   * found for that device ID.
   */
  getViewerMapping(viewerDeviceId: string): ViewerMapping | null;
  getViewerMapping(viewerDeviceId: string, mediaSessionId: string): ViewerMapping | null;
  getViewerMapping(viewerDeviceId: string, mediaSessionId?: string): ViewerMapping | null {
    if (mediaSessionId) {
      // Exact composite-key lookup
      return this.viewerMap.get(ViewerMediaBinding.compositeKey(viewerDeviceId, mediaSessionId)) ?? null;
    }
    // Legacy: return first match for this device
    for (const [, mapping] of this.viewerMap) {
      if (mapping.viewerDeviceId === viewerDeviceId) {
        return mapping;
      }
    }
    return null;
  }

  /**
   * Remove a viewer mapping by exact composite key.
   * Accepts an optional `viewerSessionId`. When provided, the mapping is
   * only removed if the stored session ID matches.
   *
   * Returns true if a mapping was removed.
   */
  removeViewerMapping(viewerDeviceId: string, mediaSessionId: string, viewerSessionId?: string): boolean {
    const key = ViewerMediaBinding.compositeKey(viewerDeviceId, mediaSessionId);
    const mapping = this.viewerMap.get(key);
    if (!mapping) return false;

    // Stale session guard: if a viewerSessionId is provided and it does not
    // match the stored mapping, reject the removal.
    if (viewerSessionId && mapping.viewerSessionId !== viewerSessionId) {
      return false;
    }

    // Stop per-viewer stats polling
    this.stopStatsForMapping(mapping);

    this.viewerMap.delete(key);
    return true;
  }

  /**
   * Remove all viewer mappings for the given media session IDs.
   * Returns the number of mappings removed.
   */
  removeMappingsForMediaSessions(mediaSessionIds: string[]): number {
    const sessionSet = new Set(mediaSessionIds);
    let removed = 0;
    for (const [key, mapping] of this.viewerMap) {
      if (sessionSet.has(mapping.mediaSessionId)) {
        this.stopStatsForMapping(mapping);
        this.viewerMap.delete(key);
        removed++;
      }
    }
    return removed;
  }

  /**
   * Get unique viewer device IDs for a logical stream.
   * Deduplicates by viewerDeviceId so a device watching both A and B variants
   * counts as one human viewer.
   */
  getUniqueViewerDevicesForLogicalStream(logicalStreamId: string): string[] {
    const devices = new Set<string>();
    for (const [, mapping] of this.viewerMap) {
      if (mapping.logicalStreamId === logicalStreamId) {
        devices.add(mapping.viewerDeviceId);
      }
    }
    return Array.from(devices);
  }

  // ─── Legacy removal (backward compat) ───────────────────────────

  /**
   * Remove a viewer from the binding map (legacy single-key path).
   *
   * When called with only `viewerDeviceId`:
   * - If the device has exactly one mapping, it is removed (pre-compare behavior).
   * - If the device has multiple mappings (compare mode), removal is SKIPPED
   *   to avoid accidentally removing an unrelated compare mapping.
   *   Callers should use removeViewerMapping() for exact targeting.
   *
   * When called with `viewerSessionId`, only the mapping(s) with a matching
   * session ID are removed.
   *
   * Cleanup is restricted to ScreenLink-owned state (mapping entry,
   * per-viewer stats polling). The peer connection is owned by the
   * VDO.Ninja SDK and is closed by the SDK itself when the viewer
   * tears down; closing it here is unsafe because it can leave the
   * SDK's internal connection map in a broken state.
   */
  removeViewer(viewerDeviceId: string, viewerSessionId?: string): boolean {
    // Find all entries for this device
    const entries = Array.from(this.viewerMap.entries())
      .filter(([, m]) => m.viewerDeviceId === viewerDeviceId);

    if (entries.length === 0) return false;

    if (viewerSessionId) {
      // Remove only entries with matching session ID
      let removed = false;
      for (const [key, mapping] of entries) {
        if (mapping.viewerSessionId === viewerSessionId) {
          this.stopStatsForMapping(mapping);
          this.viewerMap.delete(key);
          removed = true;
        }
      }
      return removed;
    }

    // No session ID provided. Legacy safe fallback:
    // - Single mapping: remove it (pre-compare behavior)
    // - Multiple mappings: skip to avoid removing an unrelated compare mapping
    if (entries.length === 1) {
      const [key, mapping] = entries[0];
      this.stopStatsForMapping(mapping);
      this.viewerMap.delete(key);
      return true;
    }

    // Multiple mappings with no session ID — do not touch (compare mode active).
    // The caller should use removeViewerMapping() with the exact mediaSessionId,
    // or removeMappingsForMediaSessions().
    console.warn(
      '[ViewerMediaBinding] removeViewer called without mediaSessionId for device with multiple mappings — skipping',
      { viewerDeviceId, mappingCount: entries.length },
    );
    return false;
  }

  /**
   * Remove a viewer by media peer UUID. Used by the host's SDK
   * `peerDisconnected` handler so that an abrupt disconnect (where
   * no `stream.leave` ever arrives) still cleans up ScreenLink-owned
   * state. The PC close itself is left to the SDK.
   */
  removeViewerByPeerUuid(mediaPeerUuid: string): boolean {
    for (const [key, mapping] of this.viewerMap) {
      if (mapping.mediaPeerUuid === mediaPeerUuid) {
        this.stopStatsForMapping(mapping);
        this.viewerMap.delete(key);
        return true;
      }
    }
    return false;
  }

  /**
   * Stage 5: Get all mapped viewers.
   * Used by StreamSessionManager.stopStream() to clean up on stream stop.
   */
  getAllViewers(): ViewerMapping[] {
    return Array.from(this.viewerMap.values());
  }

  /**
   * Get the binding token for diagnostics/debugging.
   */
  getBindingToken(token: string): BindingToken | undefined {
    return this.tokens.get(token);
  }

  /**
   * Destroy the binding manager. Terminates cleanup timer and clears all state.
   */
  destroy(): void {
    this.destroyed = true;
    this.tokens.clear();
    this.viewerMap.clear();
    this.processedRequests.clear();
    if (this.cleanupTimer) {
      clearInterval(this.cleanupTimer);
      this.cleanupTimer = null;
    }
  }

  // ── Private ──────────────────────────────────────────────────

  private startCleanup(): void {
    if (this.cleanupTimer) return;
    this.cleanupTimer = setInterval(() => {
      this.cleanupExpiredTokens();
    }, this.CLEANUP_INTERVAL_MS);
  }

  private cleanupExpiredTokens(): void {
    const now = Date.now();
    for (const [token, bt] of this.tokens) {
      if (now > bt.expiresAt) {
        this.tokens.delete(token);
      }
    }
    // Also clean up stale processed request entries (older than TTL)
    for (const [reqId, token] of this.processedRequests) {
      const bt = this.tokens.get(token);
      if (!bt) {
        this.processedRequests.delete(reqId);
      }
    }
  }

  /**
   * Stop per-viewer stats polling for a given mapping.
   * Safe to call multiple times — idempotent.
   */
  private stopStatsForMapping(mapping: ViewerMapping): void {
    try {
      const statsService = this.runtime.getMediaStatsService();
      if (statsService) {
        statsService.disconnectViewer(
          mapping.groupId,
          mapping.logicalStreamId,
          mapping.viewerDeviceId,
          mapping.mediaPeerUuid,
        );
      }
    } catch {
      // Stats cleanup is best-effort
    }
  }

  private base64URLEncode(bytes: Uint8Array): string {
    // Convert to binary string, then btoa, then make URL-safe
    let binary = "";
    for (let i = 0; i < bytes.length; i++) {
      binary += String.fromCharCode(bytes[i]);
    }
    return btoa(binary)
      .replace(/\+/g, "-")
      .replace(/\//g, "_")
      .replace(/=+$/, "");
  }

  /**
   * Resolve the target media session for a join request based on compare
   * correlation fields from the viewer's payload.
   *
   * Three scenarios:
   * 1. Neither field → legacy mode, use the primary stream.mediaSessionId.
   * 2. Only mediaSessionId → validate it belongs to this stream (primary,
   *    variant A descriptor, or variant B descriptor).
   * 3. Only compareVariantId → resolve from variant descriptor, falling
   *    back to primary for variant A if no explicit descriptor exists.
   * 4. Both fields → ensure consistency, reject mismatches.
   *
   * Returns null when the requested combination is invalid or unavailable.
   */
  private resolveTargetMediaSession(
    stream: StreamAnnouncement,
    compareVariantId?: string,
    requestedMediaSessionId?: string,
  ): { mediaSessionId: string; variantId?: string } | null {
    // ── Case 1: Legacy join (no compare fields) ─────────────────────
    if (!compareVariantId && !requestedMediaSessionId) {
      return { mediaSessionId: stream.mediaSessionId };
    }

    // ── Case 4: Both fields provided — ensure consistency ──────────
    if (compareVariantId && requestedMediaSessionId) {
      const fromVariant = this.resolveMediaSessionFromVariant(stream, compareVariantId);
      if (!fromVariant || fromVariant.mediaSessionId !== requestedMediaSessionId) {
        return null; // mismatch — reject rather than guess
      }
      return fromVariant;
    }

    // ── Case 2: Only mediaSessionId — validate it belongs to stream ─
    if (requestedMediaSessionId) {
      // Check primary stream session
      if (requestedMediaSessionId === stream.mediaSessionId) {
        return { mediaSessionId: requestedMediaSessionId, variantId: stream.primaryVariant };
      }
      // Check variant A descriptor
      if (stream.variantADescriptor?.mediaSessionId === requestedMediaSessionId) {
        return { mediaSessionId: requestedMediaSessionId, variantId: "A" };
      }
      // Check variant B descriptor
      if (stream.variantBDescriptor?.mediaSessionId === requestedMediaSessionId) {
        return { mediaSessionId: requestedMediaSessionId, variantId: "B" };
      }
      return null; // requested session not found in this stream
    }

    // ── Case 3: Only compareVariantId — resolve from variant ───────
    return compareVariantId
      ? this.resolveMediaSessionFromVariant(stream, compareVariantId)
      : null;
  }

  /**
   * Resolve media session ID from a compare variant identifier.
   *
   * Variant A: uses variantADescriptor.mediaSessionId or falls back to
   * the primary stream.mediaSessionId if no explicit A descriptor exists.
   * Variant B: requires variantBDescriptor.mediaSessionId (B is never
   * the primary stream); returns null if not configured.
   */
  private resolveMediaSessionFromVariant(
    stream: StreamAnnouncement,
    variantId: string,
  ): { mediaSessionId: string; variantId: string } | null {
    if (variantId === "A") {
      const msId = stream.variantADescriptor?.mediaSessionId ?? stream.mediaSessionId;
      return { mediaSessionId: msId, variantId: "A" };
    }
    if (variantId === "B") {
      if (!stream.variantBDescriptor?.mediaSessionId) return null;
      return { mediaSessionId: stream.variantBDescriptor.mediaSessionId, variantId: "B" };
    }
    return null; // unknown variant
  }
}
