// @ts-check
/**
 * Persistent Electron Builder configuration for ScreenLink.
 *
 * This config is committed to source control and replaces the fragile
 * temporary JSON config that was previously generated by the build script.
 *
 * NOTE: The output directory is set to a repository-root "release/" folder
 * so that all installer artifacts land at the project root alongside the
 * already-present release/ directory structure.
 */
const path = require("node:path");

/** @type {import('electron-builder').Configuration} */
const config = {
  appId: "app.screenlink.desktop",
  productName: "ScreenLink",
  directories: {
    output: path.resolve(__dirname, "../../release"),
  },
  files: [
    "dist/**/*",
    "public/**/*",
  ],
  // The after-pack script cleans up unnecessary Chromium files
  afterPack: "../../scripts/after-pack.cjs",
  win: {
    target: [
      "nsis",
      "portable",
    ],
    icon: "assets/icon.png",
  },
  nsis: {
    oneClick: false,
    perMachine: false,
    allowToChangeInstallationDirectory: true,
    // Stable artifact name that includes the version
    artifactName: "ScreenLink-Setup-${version}.${ext}",
  },
  portable: {
    artifactName: "ScreenLink-Portable-${version}.${ext}",
    // Portable builds cannot self-update — prevent electron-updater from
    // selecting the portable artifact as the update target
    unicode: false,
  },
  extraResources: [
    {
      from: "public/vendor",
      to: "vendor",
    },
    {
      from: "assets/tray-icon.png",
      to: "tray-icon.png",
    },
    {
      from: "../../native/audio-helper/build/Release/screenlink-audio-helper.exe",
      to: "screenlink-audio-helper.exe",
    },
  ],
  // Do not rebuild native modules unless specifically verified
  npmRebuild: false,
  // GitHub publish provider — the packaged app reads app-update.yml to
  // discover its update source. No token is embedded in the application.
  publish: {
    provider: "github",
    owner: "Parlaxz",
    repo: "AC-Sharescreen",
    channel: "latest",
    releaseType: "release",
    vPrefixedTagName: true,
    publishAutoUpdate: true,
  },
};

module.exports = config;
